### ISSUE TITLE
How can I do this project without Raspberry Pi ?

### ISSUE THREAD

**Issue by sinanb41** [hamuchiwa/AutoRCCar#103]
@hamuchiwa How can i do this project with ip webcam android app for streaming video and  ultrasonic sensor read and motor control from arduino ?

**Comment by sinanb41** [comment]
**My collect_training_data** 
it's working but only captures frames and stuck at Start collecting images... When i press keys happens nothing and  no print but rc_control_test working nice.
      
           import numpy as np
           import cv2
           import serial
           import pygame
           from pygame.locals import *
           import time
           import os
           import urllib

           url = 'http://192.168.14.68:8080/video'  # duzenlenecek
           stream = urllib.urlopen(url)
           stream_bytes = ''
           class CollectTrainingData(object):
    
    def __init__(self):



        # accept a single connection
        # self.connection = self.server_socket.accept()[0].makefile('rb')

        # connect to a seral port
        self.ser = serial.Serial('COM3', 115200, timeout=1) #duzenlenecek
        self.send_inst = True

        # create labels
        self.k = np.zeros((4, 4), 'float')
        for i in range(4):
            self.k[i, i] = 1
        self.temp_label = np.zeros((1, 4), 'float')

        pygame.init()
        self.collect_image()

    def collect_image(self):

        saved_frame = 0
        total_frame = 0

        # collect images for training
        print 'Start collecting images...'
        e1 = cv2.getTickCount()
        image_array = np.zeros((1, 38400))
        label_array = np.zeros((1, 4), 'float')

        # stream video frames one by one
        try:
            stream_bytes = ' '
            frame = 1
            while self.send_inst:
                stream_bytes += stream.read(1024)
                first = stream_bytes.find('\xff\xd8')
                last = stream_bytes.find('\xff\xd9')
                if first != -1 and last != -1:
                    jpg = stream_bytes[first:last + 2]
                    stream_bytes = stream_bytes[last + 2:]
                    image = cv2.imdecode(np.fromstring(jpg, dtype=np.uint8), cv2.IMREAD_GRAYSCALE)
                    
                    # select lower half of the image
                    roi = image[120:240, :]
                    
                    # save streamed images
                    cv2.imwrite('training_images/frame{:>05}.jpg'.format(frame), image)
                    
                    #cv2.imshow('roi_image', roi)
                    cv2.imshow('image', image)
                    
                    # reshape the roi image into one row array
                    temp_array = roi.reshape(1, 38400).astype(np.float32)
                    
                    frame += 1
                    total_frame += 1

                    # get input from human driver
                    for event in pygame.event.get():
                        if event.type == KEYDOWN:
                            key_input = pygame.key.get_pressed()

                            # complex orders
                            if key_input[pygame.K_UP] and key_input[pygame.K_RIGHT]:
                                print("Forward Right")
                                image_array = np.vstack((image_array, temp_array))
                                label_array = np.vstack((label_array, self.k[1]))
                                saved_frame += 1
                                self.ser.write(chr(6))

                            elif key_input[pygame.K_UP] and key_input[pygame.K_LEFT]:
                                print("Forward Left")
                                image_array = np.vstack((image_array, temp_array))
                                label_array = np.vstack((label_array, self.k[0]))
                                saved_frame += 1
                                self.ser.write(chr(7))

                            elif key_input[pygame.K_DOWN] and key_input[pygame.K_RIGHT]:
                                print("Reverse Right")
                                self.ser.write(chr(8))
                            
                            elif key_input[pygame.K_DOWN] and key_input[pygame.K_LEFT]:
                                print("Reverse Left")
                                self.ser.write(chr(9))

                            # simple orders
                            elif key_input[pygame.K_UP]:
                                print("Forward")
                                saved_frame += 1
                                image_array = np.vstack((image_array, temp_array))
                                label_array = np.vstack((label_array, self.k[2]))
                                self.ser.write('1')

                            elif key_input[pygame.K_DOWN]:
                                print("Reverse")
                                saved_frame += 1
                                image_array = np.vstack((image_array, temp_array))
                                label_array = np.vstack((label_array, self.k[3]))
                                self.ser.write('3')
                            
                            elif key_input[pygame.K_RIGHT]:
                                print("Right")
                                image_array = np.vstack((image_array, temp_array))
                                label_array = np.vstack((label_array, self.k[1]))
                                saved_frame += 1
                                self.ser.write('2')

                            elif key_input[pygame.K_LEFT]:
                                print("Left")
                                image_array = np.vstack((image_array, temp_array))
                                label_array = np.vstack((label_array, self.k[0]))
                                saved_frame += 1
                                self.ser.write('4')

                            elif key_input[pygame.K_x] or key_input[pygame.K_q]:
                                print 'exit'
                                self.send_inst = False
                                self.ser.write('0')
                                break
                                    
                        elif event.type == pygame.KEYUP:
                            self.ser.write('0')

            # save training images and labels
            train = image_array[1:, :]
            train_labels = label_array[1:, :]

            # save training data as a numpy file
            file_name = str(int(time.time()))
            directory = "training_data"
            if not os.path.exists(directory):
                os.makedirs(directory)
            try:    
                np.savez(directory + '/' + file_name + '.npz', train=train, train_labels=train_labels)
            except IOError as e:
                print(e)

            e2 = cv2.getTickCount()
            # calculate streaming duration
            time0 = (e2 - e1) / cv2.getTickFrequency()
            print 'Streaming duration:', time0

            print(train.shape)
            print(train_labels.shape)
            print 'Total frame:', total_frame
            print 'Saved frame:', saved_frame
            print 'Dropped frame', total_frame - saved_frame

        finally:
                exit(0)

           if __name__ == '__main__':
    CollectTrainingData()`

**Comment by sinanb41** [comment]
pls help  @hamuchiwa

**Comment by hamuchiwa** [comment]
If it doesn't output any text to the console, it means it's not in the pygame loop. Do you know at what line it hangs?

**Comment by Gooose1909** [comment]
* screen = pygame.display.set_mode((300, 200))*
Add this line after pygame.init()

**Comment by sinanb41** [comment]
Ok.I will try but how can i do it without rasp ?
Here is my rc_driver.py

    import threading
    import SocketServer
    import serial
    import cv2
    import numpy as np
    import math
    import urllib
           sensor_data = " " # distance data measured by ultrasonic sensor
           url = 'http://192.168.14.68:8080/video'  # duzenlenecek
           stream = urllib.urlopen(url)
           stream_bytes = ''
        class NeuralNetwork(object):

    def __init__(self):
        self.model = cv2.ml.ANN_MLP_load(mlp_xml/mlp.xml)

    def create(self):
        layer_size = np.int32([38400, 32, 4])
        self.model.create(layer_size)

    def predict(self, samples):
        ret, resp = self.model.predict(samples)
        return resp.argmax(-1)
     class RCControl(object):

    def __init__(self):
        self.serial_port = serial.Serial('COM3', 115200, timeout=1) #duzenlenecek

    def steer(self, prediction):
        if prediction == 2:
            self.serial_port.write('1')
            print("Forward")
        elif prediction == 0:
            self.serial_port.write('4')
            print("Left")
        elif prediction == 1:
            self.serial_port.write('2')
            print("Right")
        else:
            self.stop()

    def stop(self):
        self.serial_port.write('0')


    class DistanceToCamera(object):

    def __init__(self):
        # camera params
        self.alpha = 8.0 * math.pi / 180
        self.v0 = 119.907778117
        self.ay = 332.213350706

    def calculate(self, v, h, x_shift, image):
        # compute and return the distance from the target point to the camera
        d = h / math.tan(self.alpha + math.atan((v - self.v0) / self.ay))
        if d > 0:
            cv2.putText(image, "%.1fcm" % d,
                (image.shape[1] - x_shift, image.shape[0] - 20), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)
        return d


    class ObjectDetection(object):

    def __init__(self):
        self.red_light = False
        self.green_light = False
        self.yellow_light = False

    def detect(self, cascade_classifier, gray_image, image):

        # y camera coordinate of the target point 'P'
        v = 0

        # minimum value to proceed traffic light state validation
        threshold = 150     
        
        # detection
        cascade_obj = cascade_classifier.detectMultiScale(
            gray_image,
            scaleFactor=1.1,
            minNeighbors=5,
            minSize=(30, 30),
            flags=cv2.CASCADE_SCALE_IMAGE
        )

        # draw a rectangle around the objects
        for (x_pos, y_pos, width, height) in cascade_obj:
            cv2.rectangle(image, (x_pos+5, y_pos+5), (x_pos+width-5, y_pos+height-5), (255, 255, 255), 2)
            v = y_pos + height - 5
            #print(x_pos+5, y_pos+5, x_pos+width-5, y_pos+height-5, width, height)

            # stop sign
            if width/height == 1:
                cv2.putText(image, 'STOP', (x_pos, y_pos-10), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
            
            # traffic lights
            else:
                roi = gray_image[y_pos+10:y_pos + height-10, x_pos+10:x_pos + width-10]
                mask = cv2.GaussianBlur(roi, (25, 25), 0)
                (minVal, maxVal, minLoc, maxLoc) = cv2.minMaxLoc(mask)
                
                # check if light is on
                if maxVal - minVal > threshold:
                    cv2.circle(roi, maxLoc, 5, (255, 0, 0), 2)
                    
                    # Red light
                    if 1.0/8*(height-30) < maxLoc[1] < 4.0/8*(height-30):
                        cv2.putText(image, 'Red', (x_pos+5, y_pos-5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)
                        self.red_light = True
                    
                    # Green light
                    elif 5.5/8*(height-30) < maxLoc[1] < height-30:
                        cv2.putText(image, 'Green', (x_pos+5, y_pos - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
                        self.green_light = True
    
                    # yellow light
                    #elif 4.0/8*(height-30) < maxLoc[1] < 5.5/8*(height-30):
                    #    cv2.putText(image, 'Yellow', (x_pos+5, y_pos - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 255), 2)
                    #    self.yellow_light = True
        return v


    class SensorDataHandler(SocketServer.BaseRequestHandler):

    data = " "

    def handle(self):
        global sensor_data
        try:
            while self.data:
                self.data = self.request.recv(1024)
                sensor_data = round(float(self.data), 1)
                #print "{} sent:".format(self.client_address[0])
                print sensor_data
        finally:
            print "Connection closed on thread 2"


    class VideoStreamHandler(SocketServer.StreamRequestHandler):

    # h1: stop sign
    h1 = 15.5 - 10  # cm
    # h2: traffic light
    h2 = 15.5 - 10

    # create neural network
    model = NeuralNetwork()
    model.create()

    obj_detection = ObjectDetection()
    rc_car = RCControl()

    # cascade classifiers
    stop_cascade = cv2.CascadeClassifier('cascade_xml/stop_sign.xml')
    light_cascade = cv2.CascadeClassifier('cascade_xml/traffic_light.xml')

    d_to_camera = DistanceToCamera()
    d_stop_sign = 25
    d_light = 25

    stop_start = 0              # start time when stop at the stop sign
    stop_finish = 0
    stop_time = 0
    drive_time_after_stop = 0

    def handle(self):

        global sensor_data
        stream_bytes = ' '
        stop_flag = False
        stop_sign_active = True

        # stream video frames one by one
        try:
            while True:
                stream_bytes += stream.read(1024)
                first = stream_bytes.find('\xff\xd8')
                last = stream_bytes.find('\xff\xd9')
                if first != -1 and last != -1:
                    jpg = stream_bytes[first:last+2]
                    stream_bytes = stream_bytes[last+2:]
                    gray = cv2.imdecode(np.fromstring(jpg, dtype=np.uint8), cv2.IMREAD_GRAYSCALE)
                    image = cv2.imdecode(np.fromstring(jpg, dtype=np.uint8), cv2.IMREAD_UNCHANGED)

                    # lower half of the image
                    half_gray = gray[120:240, :]

                    # object detection
                    v_param1 = self.obj_detection.detect(self.stop_cascade, gray, image)
                    v_param2 = self.obj_detection.detect(self.light_cascade, gray, image)

                    # distance measurement
                    if v_param1 > 0 or v_param2 > 0:
                        d1 = self.d_to_camera.calculate(v_param1, self.h1, 300, image)
                        d2 = self.d_to_camera.calculate(v_param2, self.h2, 100, image)
                        self.d_stop_sign = d1
                        self.d_light = d2

                    cv2.imshow('image', image)
                    #cv2.imshow('mlp_image', half_gray)

                    # reshape image
                    image_array = half_gray.reshape(1, 38400).astype(np.float32)
                    
                    # neural network makes prediction
                    prediction = self.model.predict(image_array)

                    # stop conditions
                    if sensor_data is not None and sensor_data < 30:
                        print("Stop, obstacle in front")
                        self.rc_car.stop()
                    
                    elif 0 < self.d_stop_sign < 25 and stop_sign_active:
                        print("Stop sign ahead")
                        self.rc_car.stop()

                        # stop for 5 seconds
                        if stop_flag is False:
                            self.stop_start = cv2.getTickCount()
                            stop_flag = True
                        self.stop_finish = cv2.getTickCount()

                        self.stop_time = (self.stop_finish - self.stop_start)/cv2.getTickFrequency()
                        print "Stop time: %.2fs" % self.stop_time

                        # 5 seconds later, continue driving
                        if self.stop_time > 5:
                            print("Waited for 5 seconds")
                            stop_flag = False
                            stop_sign_active = False

                    elif 0 < self.d_light < 30:
                        #print("Traffic light ahead")
                        if self.obj_detection.red_light:
                            print("Red light")
                            self.rc_car.stop()
                        elif self.obj_detection.green_light:
                            print("Green light")
                            pass
                        elif self.obj_detection.yellow_light:
                            print("Yellow light flashing")
                            pass
                        
                        self.d_light = 30
                        self.obj_detection.red_light = False
                        self.obj_detection.green_light = False
                        self.obj_detection.yellow_light = False

                    else:
                        self.rc_car.steer(prediction)
                        self.stop_start = cv2.getTickCount()
                        self.d_stop_sign = 25

                        if stop_sign_active is False:
                            self.drive_time_after_stop = (self.stop_start - self.stop_finish)/cv2.getTickFrequency()
                            if self.drive_time_after_stop > 5:
                                stop_sign_active = True

                    if cv2.waitKey(1) & 0xFF == ord('q'):
                        self.rc_car.stop()
                        break

            cv2.destroyAllWindows()

        finally:
            print "Connection closed on thread 1"


      class ThreadServer(object):

    def server_thread(host, port):
        server = SocketServer.TCPServer((host, port), VideoStreamHandler)
        server.serve_forever()

    def server_thread2(host, port):
        server = SocketServer.TCPServer((host, port), SensorDataHandler)
        server.serve_forever()

    # distance_thread = threading.Thread(target=server_thread2, args=('192.168.1.100', 8002))
    # distance_thread.start()

      if __name__ == '__main__':
    ThreadServer()

**Comment by Gooose1909** [comment]
I am not familiar with android
Look into this ptoject
He used similar approach of using mobile device for stream

https://github.com/dps/nnrccar

**Comment by sinanb41** [comment]
Android part is just video streaming it can be pc camera too.

**Comment by sinanb41** [comment]
I mean it is not about android coding I will attach small old android phone and use ip webcam app for streaming' http://192.168.14.68:8080/video

**Comment by sinanb41** [comment]
For car movement I will connect HC06 bluetooth module and my PC then COM port will send data

**Comment by sinanb41** [comment]
@hamuchiwa  How can I do this project without Raspberry Pi ?

**Comment by hamuchiwa** [comment]
@sinanb41 I assume you are asking how to do this project with an ip camera, take a look at [this](https://github.com/hamuchiwa/AutoRCCar/issues/56).

**Comment by tiachachat** [comment]
@sinanb41 we are in the same boat
I changed this project a little bit
I used this app to streaming video "IP Webcam" https://play.google.com/store/apps/details?id=com.pas.webcam&hl=en
but i hava probleme with training the model
this is the code 

import numpy as np
import cv2
import time
import requests
import threading
from threading import Thread, Event, ThreadError
import serial
import pygame
from pygame.locals import *
import os
url = 'http://192.168.1.6:8080/video'


inst = True
class CollectTrainingData(object):

  def __init__(self):
    
    self.stream = requests.get(url, stream=True)
    self.thread_cancelled = False
    self.thread = Thread(target=self.run)
    print "camera initialised"
    self.thread.start()
    self.ser = serial.Serial('COM3', 115200, timeout=1)
    self.k = np.zeros((4, 4), 'float')
    for i in range(4):
        self.k[i, i] = 1
    self.temp_label = np.zeros((1, 4), 'float')
    pygame.init()
    self.inst = True
    
    
    
    
  
    
  def run(self):
    screen = pygame.display.set_mode((320,240))
    saved_frame = 0
    total_frame = 0

    # collect images for training
    print 'Start collecting images...'
    e1 = cv2.getTickCount()
    image_array = np.zeros((1, 38400))
    label_array = np.zeros((1, 4), 'float')
    
    try:
      bytes=''
      frame = 1
      while self.inst:
        
        bytes+=self.stream.raw.read(1024)
        a = bytes.find('\xff\xd8')
        b = bytes.find('\xff\xd9')
        if a!=-1 and b!=-1:
          jpg = bytes[a:b+2]
          bytes= bytes[b+2:]
          img = cv2.imdecode(np.fromstring(jpg, dtype=np.uint8),cv2.IMREAD_GRAYSCALE)
          # select lower half of the image
          roi = img[120:240, :]

          # save streamed images
          cv2.imwrite('training_images/frame{:>05}.jpg'.format(frame), img)
           
          cv2.imshow('cam',img)

          # reshape the roi image into one row array
          temp_array = roi.reshape(1, 38400).astype(np.float32)
          frame += 1
          total_frame += 1
          
          # get input from human driver
          for event in pygame.event.get():
              if event.type == KEYDOWN:
                  key_input = pygame.key.get_pressed()

                  # complex orders
                  if key_input[pygame.K_UP] and key_input[pygame.K_RIGHT]:
                      print("Forward Right")
                      image_array = np.vstack((image_array, temp_array))
                      label_array = np.vstack((label_array, self.k[1]))
                      saved_frame += 1
                      self.ser.write(chr(6))

                  elif key_input[pygame.K_UP] and key_input[pygame.K_LEFT]:
                      print("Forward Left")
                      image_array = np.vstack((image_array, temp_array))
                      label_array = np.vstack((label_array, self.k[0]))
                      saved_frame += 1
                      self.ser.write(chr(7))

                  elif key_input[pygame.K_DOWN] and key_input[pygame.K_RIGHT]:
                      print("Reverse Right")
                      self.ser.write(chr(8))
                            
                  elif key_input[pygame.K_DOWN] and key_input[pygame.K_LEFT]:
                      print("Reverse Left")
                      self.ser.write(chr(9))

                  # simple orders
                  elif key_input[pygame.K_UP]:
                      print("Forward")
                      saved_frame += 1
                      image_array = np.vstack((image_array, temp_array))
                      label_array = np.vstack((label_array, self.k[2]))
                      self.ser.write(chr(1))

                  elif key_input[pygame.K_DOWN]:
                      print("Reverse")
                      saved_frame += 1
                      image_array = np.vstack((image_array, temp_array))
                      label_array = np.vstack((label_array, self.k[3]))
                      self.ser.write(chr(2))
                            
                  elif key_input[pygame.K_RIGHT]:
                      print("Right")
                      image_array = np.vstack((image_array, temp_array))
                      label_array = np.vstack((label_array, self.k[1]))
                      saved_frame += 1
                      self.ser.write(chr(3))

                  elif key_input[pygame.K_LEFT]:
                      print("Left")
                      image_array = np.vstack((image_array, temp_array))
                      label_array = np.vstack((label_array, self.k[0]))
                      saved_frame += 1
                      self.ser.write(chr(4))

                  elif key_input[pygame.K_x] or key_input[pygame.K_q]:
                      print 'exit'
                      self.inst = False
                      self.ser.write(chr(0))
                      break
                                    
              elif event.type == pygame.KEYUP:
                  self.ser.write(chr(0))

          
          if cv2.waitKey(1) ==27:
            exit(0)
      
      # save training images and labels
      train = image_array[1:, :]
      train_labels = label_array[1:, :]

      # save training data as a numpy file
      file_name = str(int(time.time()))
      directory = "training_data"
      if not os.path.exists(directory):
          os.makedirs(directory)
      try:    
          np.savez(directory + '/' + file_name + '.npz', train=train, train_labels=train_labels)
      except IOError as e:
          print(e)

      e2 = cv2.getTickCount()
      # calculate streaming duration
      time0 = (e2 - e1) / cv2.getTickFrequency()
      print 'Streaming duration:', time0

      print(train.shape)
      print(train_labels.shape)
      print 'Total frame:', total_frame
      print 'Saved frame:', saved_frame
      print 'Dropped frame', total_frame - saved_frame
    except ThreadError:
      self.thread_cancelled = True
        
        
  
      
    
 

  
    
if __name__ == "__main__":
  
  CollectTrainingData()

**Comment by VishalWrench** [comment]
## I am also trying to implement using phone camera (without rasp pi).    @sinanb41 @hamuchiwa  I have tried running this code using ip-camera android app for streaming when i press arrow keys in my keyboard it is not saving images and exiting out of the loop. when i have removed these two lines 

### image_array = np.vstack((image_array, temp_array))
### label_array = np.vstack((label_array, self.k[2])) 

### it send the data to serial and my car moves but my camera images are not saved (as i have removed those lines)
import numpy as np
import cv2
import serial
import pygame
from pygame.locals import *
import time
import os
import urllib

url = 'http://100.86.250.34:8080/video'  # duzenlenecek
stream = urllib.urlopen(url)
stream_bytes = ''
class CollectTrainingData(object):
    def __init__(self):



        # accept a single connection
        # self.connection = self.server_socket.accept()[0].makefile('rb')

        # connect to a serial port
        self.ser = serial.Serial('COM3', 115200, timeout=1) #duzenlenecek
        self.send_inst = True

        # create labels
        self.k = np.zeros((4, 4), 'float')
        for i in range(4):
            self.k[i, i] = 1
        self.temp_label = np.zeros((1, 4), 'float')

        pygame.init()
        pygame.display.set_mode((400, 400))
        self.collect_image()

    def collect_image(self):

        saved_frame = 0
        total_frame = 0
        shapeu = 320*240

        # collect images for training
        print 'Start collecting images...'
        print("Press 'q' or 'x' to finish...")
        e1 = cv2.getTickCount()
        image_array = np.empty((0, shapeu))
        label_array = np.empty((0, 4))

        # stream video frames one by one
        try:
            stream_bytes = ' '
            frame = 1
            while self.send_inst:
                stream_bytes += stream.read(1024)
                first = stream_bytes.find('\xff\xd8')
                last = stream_bytes.find('\xff\xd9')
                if first != -1 and last != -1:
                    jpg = stream_bytes[first:last + 2]
                    stream_bytes = stream_bytes[last + 2:]
                    image = cv2.imdecode(np.frombuffer(jpg, dtype=np.uint8), cv2.IMREAD_GRAYSCALE)

                    # select lower half of the image
                    height, width = image.shape
                    roi = image[int(height/2):height, :]
                    #roi = image[120:240, :]

                    #cv2.imshow('roi_image', roi)
                    cv2.imshow('image', image)
                    # save streamed images
                    cv2.imwrite('training_images/frame{:>05}.jpg'.format(frame), image)



                    # reshape the roi image into one row array
                    #temp_array = roi.reshape(1, 76800).astype(np.float32)
                    temp_array = roi.reshape(1, int(height/2) * width).astype(np.float32)

                    frame += 1
                    total_frame += 1

                    # get input from human driver
                    for event in pygame.event.get():
                        if event.type == KEYDOWN:
                            key_input = pygame.key.get_pressed()

                            # complex orders
                            if key_input[pygame.K_UP] and key_input[pygame.K_RIGHT]:
                                print("Forward Right")
                                image_array = np.vstack((image_array, temp_array))
                                label_array = np.vstack((label_array, self.k[1]))
                                saved_frame += 1
                                self.ser.write(chr(6).encode())

                            elif key_input[pygame.K_UP] and key_input[pygame.K_LEFT]:
                                print("Forward Left")
                                image_array = np.vstack((image_array, temp_array))
                                label_array = np.vstack((label_array, self.k[0]))
                                saved_frame += 1
                                self.ser.write(chr(7).encode())

                            elif key_input[pygame.K_DOWN] and key_input[pygame.K_RIGHT]:
                                print("Reverse Right")
                                self.ser.write(chr(8).encode())

                            elif key_input[pygame.K_DOWN] and key_input[pygame.K_LEFT]:
                                print("Reverse Left")
                                self.ser.write(chr(9).encode())

                            # simple orders
                            elif key_input[pygame.K_UP]:
                                print("Forward")
                                saved_frame += 1
                                image_array = np.vstack((image_array, temp_array))
                                label_array = np.vstack((label_array, self.k[2]))
                                self.ser.write(chr(1).encode())

                            elif key_input[pygame.K_DOWN]:
                                print("Reverse")
                                #saved_frame += 1
                                #image_array = np.vstack((image_array, temp_array))
                                #label_array = np.vstack((label_array, self.k[3]))
                                self.ser.write(chr(2).encode())

                            elif key_input[pygame.K_RIGHT]:
                                print("Right")
                                image_array = np.vstack((image_array, temp_array))
                                label_array = np.vstack((label_array, self.k[1]))
                                saved_frame += 1
                                self.ser.write(chr(3).encode())

                            elif key_input[pygame.K_LEFT]:
                                print("Left")
                                image_array = np.vstack((image_array, temp_array))
                                label_array = np.vstack((label_array, self.k[0]))
                                saved_frame += 1
                                self.ser.write(chr(4).encode())

                            elif key_input[pygame.K_x] or key_input[pygame.K_q]:
                                print 'exit'
                                self.send_inst = False
                                self.ser.write(chr(0).encode())
                                self.ser.close()
                                break

                        elif event.type == pygame.KEYUP:
                            self.ser.write(chr(0).encode())

                    if cv2.waitKey(1) & 0xFF == ord('q'):
                        break

            # save training images and labels
            #train = image_array[1:, :]
            #train_labels = label_array[1:, :]

            # save training data as a numpy file
            file_name = str(int(time.time()))
            directory = "training_data"
            if not os.path.exists(directory):
                os.makedirs(directory)
            try:
                np.savez(directory + '/' + file_name + '.npz', train=image_array, train_labels=label_array)
            except IOError as e:
                print(e)

            e2 = cv2.getTickCount()
            # calculate streaming duration
            time0 = (e2 - e1) / cv2.getTickFrequency()
            print 'Streaming duration:', time0

            print(image_array.shape)
            print(label_array.shape)
            print 'Total frame:', total_frame
            print 'Saved frame:', saved_frame
            print 'Dropped frame', total_frame - saved_frame



        finally:
            exit(0)

if __name__ == '__main__':
    CollectTrainingData()
    
### Here is the screenshot of the output.When i press forward key it prints forward and doesn't save image and exits from the loop and when i press backward key it send signal to the car it moves backward as i have removed the array coversion lines. help me with this plzzz.
### Thanks in advance,  Waiting for your reply
![Screenshot (49)](https://user-images.githubusercontent.com/48159854/54236788-72ec0180-453a-11e9-998a-8f12f6ba72a6.png)
