### ISSUE TITLE
PI的视频无法传输到PC服务器

### ISSUE THREAD

**Issue by Maxxiezhu** [hamuchiwa/AutoRCCar#107]
PC和PI已经连接了同一个局域网如下图
![360 16570212110857](https://user-images.githubusercontent.com/37396232/39877917-b2897782-54a9-11e8-8604-1bcc27901840.png)
端口也是一致的。
![360 16250104151515](https://user-images.githubusercontent.com/37396232/39878104-1e190cf6-54aa-11e8-91b0-da846ad8a248.png)
![360 16550430318561](https://user-images.githubusercontent.com/37396232/39878106-1f7632d6-54aa-11e8-9265-38769d19d8dc.png)

但是，当我PI上运行了stream_client，然后PC运行了collect_training_data
我PI上摄像头没有亮灯（摄像头测试过了没有坏），也没有拍摄的视频显示出来，PC段也没有任何反应，PC桌面一直是没有反应的命令行窗口（win7）
请问一下这个是什么问题？朋友。对了加你微信或者QQ方便不。我是在校大学生，想请教你更多的问题。
@hamuchiwa

**Comment by hamuchiwa** [comment]
测试文件有没有试过，stream_server_test.py，有没有视频窗口弹出来?
微信：343162765
