### ISSUE TITLE
请用opencv训练红绿灯的分类器的正负样本您是怎么选取的，方便提供一下训练使用的数据吗？

### ISSUE THREAD

**Issue by RongjieChen** [hamuchiwa/AutoRCCar#108]
请用opencv训练红绿灯的分类器的正负样本您是怎么选取的，方便提供一下训练使用的数据吗？

**Comment by hamuchiwa** [comment]
红绿灯是淘宝上买的，我用手机拍的然后抠图。负样本只要没有红绿灯就行，pi camera拍的地面。
![r01](https://user-images.githubusercontent.com/9021941/40086980-ac3aa838-586e-11e8-87a8-6552fc235132.jpg)
![frame00510](https://user-images.githubusercontent.com/9021941/40086985-ae05efc4-586e-11e8-8936-b6bb2dfb65b8.jpg)
