### ISSUE TITLE
How to control RC car Speed ?

### ISSUE THREAD

**Issue by marcusvn** [hamuchiwa/AutoRCCar#109]
My Car is really fast, and It can't control while i have trained. How I can decrease speed of auto RC car ? What is your solution? Can you describe detail for help me plz @hamuchiwa ?

**Comment by hamuchiwa** [comment]
我当时是加了一个电位器，不过效果一般，有条件的话还是找一个速度可调节的遥控车来的更容易一些。

**Comment by marcusvn** [comment]
How can I connect potentiometer with motor of RC Car ?

**Comment by hamuchiwa** [comment]
I just put a potentiometer between motor and incoming wire.

**Comment by marcusvn** [comment]
What potentiometer did you use?10k or 5k or what ? and Can you share for me for circuit ? or website did you use ?thanks for helping !

**Comment by hamuchiwa** [comment]
I don't really remember, my rc car was disassembled long long time ago, but pick the smaller one. You can just connect one potentiometer pin to the motor, and connect another pin to the wire that originally connected to the motor. 
                                    ↓
     _____ -  M + _____www ______

**Comment by RajdeepMondal** [comment]
Why dont u use PWM?

**Comment by marcusvn** [comment]
How I can use PWM ? @RajdeepMondal

**Comment by RajdeepMondal** [comment]
If you are using a motor driver directly supply a PWM into the enable pin
of the motor driver...
