### ISSUE TITLE
No tutorial page: Drive a Lamborghini With Your Keyboard

### ISSUE THREAD

**Issue by SaturnRobolabs** [hamuchiwa/AutoRCCar#113]
i wanted to know the insights of the arduino code. when i opened the link

Inspired by this aiticle: Drive a Lamborghini With Your Keyboard

it shows no page. can u explain it please

**Comment by hamuchiwa** [comment]
it's [here](https://web.archive.org/web/20130601112348/http://thelivingpearl.com/2013/01/04/drive-a-lamborghini-with-your-keyboard/)
