### ISSUE TITLE
Could you help me with the connections?

### ISSUE THREAD

**Issue by chouhansolo** [hamuchiwa/AutoRCCar#114]
Hi, I am new to python and using raspberry pi. I found this project and I would love to see my RC car doing what yours does but the major problem I am facing is I do not know which pins of the Pi and arduino to connect. Could you maybe help me with understanding the connections? Thanks in advance.

**Comment by hamuchiwa** [comment]
For Arduino, take a look at #61 and #88 
For Raspberry pi, #33
