### ISSUE TITLE
RC Car Speed Control

### ISSUE THREAD

**Issue by IbrahimOjeili** [hamuchiwa/AutoRCCar#119]
Hello, I am in the process of collecting training data using different tracks made of white paper. I have a couple of questions.

1- The RC car I have used for this project is 1:14 scale and is too fast for the track. How can I reduce the speed?

2- What does the pi cam calibration code do exactly?

3- Does the track have to take up atleast half of the picture when captured by the camera? At the moment the track is about 35% of the picture.

Thank you so much for your help!

**Comment by hamuchiwa** [comment]
I guess you have found your answers already, it's actually easier to buy a rc car with speed control; calibration is to get pi camera matrix (refer to OpenCV doc for more detail), if you are using pi camera, then this is optional; it doesn't, if 35% works for you then congrats!
