### ISSUE TITLE
Simultaneous streaming video and receiving commands to control a car

### ISSUE THREAD

**Issue by SumekQQ** [hamuchiwa/AutoRCCar#123]
Is it possible to simultaneously stream video from a raspberry PI camera and receive a command to control the car?
Because i try building own construction somethink like a tank and i want use only one microcontroller(Raspberry Pi).
It's possible?

**Comment by BreakerMark** [comment]
Yes. You can use a new port to send the control code back to the Raspberry Pi so that you can use the Raspberry Pi to control the Arduino.
