### ISSUE TITLE
W jaki sposób nauczyć haara?

### ISSUE THREAD

**Issue by xor256** [hamuchiwa/AutoRCCar#13]
Twój kod nie zawiera żadnych obrazów, czy jest mozliwosc zrobienia minimalnego Makefile z przykładowymi danymi? Nie udaje mi się uruchomic programu do nauki w OpenCV

Tree Classifier
Stage
+---+
|  0|
+---+

Number of features used : 125199

Parent node: NULL

*** 1 cluster ***
POS: 12 12 1.000000
Invalid background description file.
opencv_haartraining: /builddir/build/BUILD/opencv-2.4.12.3/apps/haartraining/cvhaartraining.cpp:1393: void icvGetNextFromBackgroundData(CvBackgroundData*, CvBackgroundReader*): Assertion `0' failed.
./zz2a.sh: linia 10:  3898 Aborted                 (zrzut pamięci) opencv_haartraining -data hdgh -vec przyklady.txt -bg negatywne.txt -nstages 2 -nsplits 2 -minhitrate 0.01 -maxfalsealarm 0.999 -npos 12 -nneg 4 -w 20 -h 20 -nonsym -mem 1024 -mode ALL -minpos 10

mógłbys mi jakos pomóc?

**Comment by isrugeek** [comment]
Can you use English For Better understanding? then we can help you!
