### ISSUE TITLE
Blog link not working

### ISSUE THREAD

**Issue by scud3r1a** [hamuchiwa/AutoRCCar#130]
The following link (reference) does not work anymore:
http://thelivingpearl.com/2013/01/04/drive-a-lamborghini-with-your-keyboard/
Does anybody have the source?

Thanks.

**Comment by hamuchiwa** [comment]
A quick google search, [this post](https://www.instructables.com/id/Python-Arduino-CarControl-v03/) seems to be very similar to the original one.
