### ISSUE TITLE
Error when run rc_drive.py

### ISSUE THREAD

**Issue by Abdalhad** [hamuchiwa/AutoRCCar#131]
Hi hamuchiwa 
all codes run fine but when i run rc_drive.py
to start autonomous driving
get this : 

Traceback (most recent call last):
  File "E:\AutoRCCar-master\computer\rc_driver.py", line 29, in <module>
    class VideoStreamHandler(socketserver.StreamRequestHandler):
  File "E:\AutoRCCar-master\computer\rc_driver.py", line 38, in VideoStreamHandler
    nn.load_model("saved_model/nn_model.xml")
  File "E:\AutoRCCar-master\computer\model.py", line 88, in load_model
    self.model = cv2.ml.ANN_MLP_load(path)
AttributeError: 'module' object has no attribute 'ANN_MLP_load'

------------------------------------------------------------------------------------------------
use windows 10-64bit
'OpenCV:', '3.1.0')
('Numpy : ', '1.15.4')
('Python:', '2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]')

**Comment by hamuchiwa** [comment]
Upgrade your OpenCV, if you followed the environment set up, you should have the latest version installed. I had OpenCV 3.4, it worked fine.
