### ISSUE TITLE
Ultrasonic test

### ISSUE THREAD

**Issue by kalmastenitin** [hamuchiwa/AutoRCCar#132]
I am trying to run Ultrasonic server test & ultrasonic client - I m getting Errors 
on server (streaming sensor_data = float(self.connection.recv(1024))
ValueError: could not convert string to float)
on client (TypeError: a bytes-like object is required, not 'str')

all things set up properly

**Comment by hamuchiwa** [comment]
@kalmastenitin Python3 and Python2 handle `str` differently. What's the default python on Raspbian?
For using python3 on raspberry pi,  you can change`ultrasonic_client.py` line 52 to `client_socket.send(str(distance).encode('utf-8))`

**Comment by kalmastenitin** [comment]
it worked for me now i am using python3.7 on server and client side. Thanks
