### ISSUE TITLE
How to connect esp8266 to RC controller

### ISSUE THREAD

**Issue by OZhang** [hamuchiwa/AutoRCCar#133]
I've tried to connect esp8266 to the RC controller some days, but I never make it. Could someone tell me how should I do it?

PS: I've check #61 and #88, still cannot make it work.
Thanks in advance.
my rc controller

![xkextvjrt4cxggil7gmwxa_thumb_391e](https://user-images.githubusercontent.com/11295037/50837492-b7222080-1396-11e9-9ae9-8ba9696278c0.jpg)
![vsn6c u7t1imkmpfmy7kqw_thumb_391d](https://user-images.githubusercontent.com/11295037/50837502-bd180180-1396-11e9-8b49-bccea851e03d.jpg)

**Comment by kxrf97** [comment]
how you connect this with arduino
