### ISSUE TITLE
Components to buy..?

### ISSUE THREAD

**Issue by SaiSurya9999** [hamuchiwa/AutoRCCar#134]
Can you please provide me the check list of the components to buy...?
In the traffic light section i see another ino file which has to be burned on another audrino. by that i think two audrino are required a little bit of confusion please help me..

**Comment by hamuchiwa** [comment]
@SaiSurya9999 Raspberry pi, pi camera, ultrasonic sensor, some resistors and wires, and only one Arduino board.  For connections, take a look #124

**Comment by SaiSurya9999** [comment]
Thank you so much @hamuchiwa ...!!
