### ISSUE TITLE
Host and client port numbers

### ISSUE THREAD

**Issue by SaiSurya9999** [hamuchiwa/AutoRCCar#141]
How to know our host and port numbers which we have to change in the code as per our systems...??
(I mean in the server and client programs....*Ultrasonic Sensor and also *PI **cam)**
----------------------------Thank you-------------------------------------------

**Comment by hamuchiwa** [comment]
@SaiSurya9999 You can leave the port numbers as they are. To find your ip address, on windows, type `ipconfig`, on linux/mac, type `ifconfig`.
