### ISSUE TITLE
Stop Sign and traffic light detection and Neural network details

### ISSUE THREAD

**Issue by SaiSurya9999** [hamuchiwa/AutoRCCar#145]
Are stop sign and traffic lights are pre trained..??
Did you use tensorflow in this project ?? or else what have you used in the neural network..??

**Comment by SaiSurya9999** [comment]
What should we do with traffic light ino file..??

**Comment by hamuchiwa** [comment]
Yes, they are pertained. This project was made many years ago, Tensorflow was not used. 
If you make your own traffic light based on geek1111's schema, then you need that file.
Keep in mind, traffic light classifier only works for the "traffic light" you see in video, while stop sign classifier was trained with real stop sign images.
