### ISSUE TITLE
Tutorial.

### ISSUE THREAD

**Issue by Ola1234** [hamuchiwa/AutoRCCar#149]
Hello, I loved the project, so I would like to ask if anyone could do a tutorial on how to make this car (parts, connections). Sorry for the boring question, but I found it really interesting. (also, I'm a beginner)

**Comment by hamuchiwa** [comment]
@Ola1234 You can read this [page](https://zhengludwig.wordpress.com/projects/self-driving-rc-car/) if it helps. For connections, take a look #124.
