### ISSUE TITLE
rc control issue

### ISSUE THREAD

**Issue by arunph** [hamuchiwa/AutoRCCar#152]
hi sir i have an issue with the rc control using keyboard.since i had connected aurdino to the rc control and connected the respective pins 6 7 9 10 to left,right,forward,backward.but when i press arrow keys on keyboard light on the rc control blinks but doesn't moves.

**Comment by hamuchiwa** [comment]
Hi, maybe something wrong with the connections between arduino and controller,  as you mentioned the light does blink. Check out #88 if it helps.
