### ISSUE TITLE
Training 

### ISSUE THREAD

**Issue by uditshinghal** [hamuchiwa/AutoRCCar#153]
hi,
First when I am trying to run training_data_model.py, it is running properly,
but when I am trying to connect the client file stream_client.py it is showing the following error on the conda prompt which is running the training_data_model.py
Please help me I need to finish this project urget.
I hope to hear from you soon.
![capture](https://user-images.githubusercontent.com/19620278/53264630-16977e00-3702-11e9-98e0-25257bb7585e.PNG)

**Comment by hamuchiwa** [comment]
Since you are using windows, don't forget to change the port to match the one on your windows machine. You can find this via Arduino IDE, click "Tools" then "Port". Then replace the one on line 174 in `collect_training_data.py`.
