### ISSUE TITLE
Collecting dataset

### ISSUE THREAD

**Issue by FediSalhi** [hamuchiwa/AutoRCCar#158]
How many frames are needed for a good training? How many frame did you save for your model? 
What is the camera calibration used for? Do we need to do the calibration only for distance measurement ?
Do we need to do any calibration before collecting the dataset?

**Comment by hamuchiwa** [comment]
@FediSalhi If your track is simple, 200 images are okay. Calibration is for distant measurement, if you are using pi camera, you may leave that alone. Take a look at #139 in case you have similar doubts.

**Comment by arunph** [comment]
Kindly help me with excution steps for training the model.
