### ISSUE TITLE
Test stream

### ISSUE THREAD

**Issue by akilystic** [hamuchiwa/AutoRCCar#159]
I am getting the following errors when i run camera test streqam files on raspi and laptop.

error on laptop: (numpy is installed)
akash@asp:~/Downloads/AutoRCCar-master/test$ python stream_server_test.py
Traceback (most recent call last):
  File "stream_server_test.py", line 3, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

on raspi:
![screenshot from 2019-03-04 14-33-03](https://user-images.githubusercontent.com/21705393/53721997-80deba00-3e8a-11e9-91d6-089ce6af59cc.png)

**Comment by hamuchiwa** [comment]
If you have created a conda environment, make sure to activate it before running the code.
`source activate auto-rccar`
