### ISSUE TITLE
Traffic signal not detected

### ISSUE THREAD

**Issue by sundar19** [hamuchiwa/AutoRCCar#163]
Mr.hamuchiwa
I showed a red led before camera but it's not detected. I can't find any readymade traffic signals in market.so what parameters are important in making the traffic signal
Thank you

**Comment by hamuchiwa** [comment]
The traffic light classifier included in this project only works for the light you see in the video, certainly you could make one and train a model on that. I don't quite follow what you meant by parameters, I think as long as it looks like a traffic light, shape and edges are clear then it should be fine.

**Comment by sundar19** [comment]
Thank You Mr.Hamuchiwa
