### ISSUE TITLE
I got a error. Please help!

### ISSUE THREAD

**Issue by BjasNL** [hamuchiwa/AutoRCCar#17]
Hi I try to run picam_Calibration and I got the follow error. Please do you know how I can fix this?

cd '/Users/bas/Desktop/' && '/usr/local/bin/pythonw'  '/Users/bas/Desktop/picam_calibratio.py'  && echo Exit status: $? && exit 1
imac:~ bas$ cd '/Users/bas/Desktop/' && '/usr/local/bin/pythonw'  '/Users/bas/Desktop/picam_calibratio.py'  && echo Exit status: $? && exit 1
OpenCV Error: Assertion failed (nimages > 0) in calibrateCamera, file /Users/bas/opencv/modules/calib3d/src/calibration.cpp, line 3357
Traceback (most recent call last):
  File "/Users/bas/Desktop/picam_calibratio.py", line 47, in <module>
    retval, cameraMatrix, distCoeffs, rvecs, tvecs = cv2.calibrateCamera(object_points, image_points, (w, h), None, None)
cv2.error: /Users/bas/opencv/modules/calib3d/src/calibration.cpp:3357: error: (-215) nimages > 0 in function calibrateCamera

**Comment by hamuchiwa** [comment]
Hmm... it seems something goes wrong with your image files. Check out the camera calibration tutorial from [here](http://opencv-python-tutroals.readthedocs.org/en/latest/py_tutorials/py_calib3d/py_calibration/py_calibration.html).
