### ISSUE TITLE
Please help me with circuit connection

### ISSUE THREAD

**Issue by Devanshice020** [hamuchiwa/AutoRCCar#171]
I have bought the rc car and following is remote circuit of the car.Can you please help me with it that where to connect wires.
Please help it's urgent 
![IMG_20190320_112459 (1)](https://user-images.githubusercontent.com/46786247/54662544-5b95b100-4b04-11e9-911c-ca80160c3460.jpg)
![IMG_20190320_112444](https://user-images.githubusercontent.com/46786247/54662546-5b95b100-4b04-11e9-8875-9c855ad5a7ef.jpg)

**Comment by VishalWrench** [comment]
#164  this issue will help you with that. Good luck

**Comment by Devanshice020** [comment]
It helped. Thank you @VishalWrench
