### ISSUE TITLE
A small Bug

### ISSUE THREAD

**Issue by SaiSurya9999** [hamuchiwa/AutoRCCar#177]
![bug](https://user-images.githubusercontent.com/46582001/54925485-643b1c80-4f34-11e9-8b98-42a3fa4165ba.png)
There are equal no of forward action calls for the same obstacle detected which is not stopping my car please help me...
Ignore that  prediction 5 printing it doesnt mean anything..

**Comment by SaiSurya9999** [comment]
I have used delay functions in audrino board program to slow the car is this causing any problem please check...
Here is the forward function which i modified to slow the car speed..
void forward(int time){
digitalWrite(forward_pin, HIGH);
delay(20);
digitalWrite(forward_pin, LOW);
delay(time); // time = 50
}

**Comment by Sirajabudabe** [comment]
Hi @SaiSurya9999 
Did the rc_driver.py worked fine for you or did you face any problem in connection ,if so please let me know what is it 
my problem that the rc_driver_nn_only.py worked but the rc_driver.py didn't because some problems in connection

**Comment by SaiSurya9999** [comment]
Video stream and ultrasonic data connection is fine i didn't get any error like broken pipe.

**Comment by hamuchiwa** [comment]
@SaiSurya9999 Is this duplicated with your #174?

**Comment by SaiSurya9999** [comment]
Ohh yes sorry..!!
