### ISSUE TITLE
ERROR OF BROKEN PIPE WHILE TESTING ULTRASONIC SENSOR_CLIENT.PY

### ISSUE THREAD

**Issue by Devanshice020** [hamuchiwa/AutoRCCar#178]
![12](https://user-images.githubusercontent.com/46786247/54987715-11687000-4fdb-11e9-9a1f-e333bb06a4db.PNG)
![123](https://user-images.githubusercontent.com/46786247/54987716-12010680-4fdb-11e9-97f9-572aaf426475.PNG)
 i am facing this error of broken pipe while testing the client and server side of ultrasonic sensor.. it counts upto around 20 measurements and perfectly streams to the server side and then there is this error in the client side . please can you look into it @hamuchiwa , it is very urgent .

**Comment by hamuchiwa** [comment]
@Devanshice020 Because server only runs for 10 second, so you see total 20 values printed (1/0.5*10=20). When server exits, you get a broken pipe error on the client side.

**Comment by SaiSurya9999** [comment]
@hamuchiwa please respond to #177.

**Comment by Devanshice020** [comment]
so @hamuchiwa  how do i resolve my problem sir?..i want to get measurements as long as i want as in the final testing , the car has to detect the obstacle  till i manually shut it off? how do i extend the server time to infinite or some thing? pls help sir @hamuchiwa

**Comment by hamuchiwa** [comment]
@Devanshice020 Just remove line 32, 32 from `ultrasonic_server_test.py`.
