### ISSUE TITLE
OS WINERROR 10048 :Only one socket address is permitted

### ISSUE THREAD

**Issue by Devanshice020** [hamuchiwa/AutoRCCar#181]
i am attaching a screenshot of the error i am receiving while running **_collecttrainingdata.py_**.
how to resolve this error? it is only allowing one socket address of usage, how to resolve it to use it @hamuchiwa Sir. pls have a look into it. Just to mention smthing, you are a real inspiration for students like us. waiting for your response @hamuchiwa 
![error](https://user-images.githubusercontent.com/46786247/55076487-8b702600-50bb-11e9-83c4-e6fcfdcae9db.PNG)

**Comment by hamuchiwa** [comment]
After collecting data, press `q` to exit properly. Other ways are kill the process or restart your console/IDE.
