### ISSUE TITLE
error while running rc_drive.py

### ISSUE THREAD

**Issue by Devanshice020** [hamuchiwa/AutoRCCar#185]
An exception has occurred, use %tb to see the full traceback.

SystemExit

C:\Users\Krishna\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3304: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

I am getting this error while running rc_driver.py

**Comment by SaiSurya9999** [comment]
It may be libraries issue do run environment.yml file to create environment. And then activate it before execution. Even though if problem exist compare the versions with repository versions.

**Comment by hamuchiwa** [comment]
@Devanshice020 Does it say what exception?

**Comment by Devanshice020** [comment]
File "C:/Users/Krishna/Desktop/RPI/AutoRCCar-master/computer/rc_driver.py", line 160, in handle
    sys.exit()

SystemExit

It shows this error while i run %tb in shell

**Comment by hamuchiwa** [comment]
@Devanshice020 Run the code in a terminal instead, sys.eixt() will exit python.

**Comment by Devanshice020** [comment]
Thanks @hamuchiwa for your help and support I have solved this issue by importing every function from rc_driver_help.py manually.
And also by defining 
d_sensor_thresh = 30
d_stop_light_thresh = 25
d_stop_sign = d_stop_light_thresh
d_light = d_stop_light_thresh
outside every function.

**Comment by apoorvyadav1111** [comment]
@hamuchiwa i have same issue. It says exception occurred and system exit. Please help

**Comment by hamuchiwa** [comment]
@apoorvyadav1111 @Devanshice020 #174
