### ISSUE TITLE
Serial output too fast

### ISSUE THREAD

**Issue by MyFirstRoboticProject** [hamuchiwa/AutoRCCar#188]
@hamachiwa
When running the rc_driver.py (or nn only), the forward output responses on a straight track comes too fast and quickly (I get 10 forward responses in just 1 second). Due to this my car is unable to keep up and even if I terminate the code (i.e. rc_driver.py) it keeps on running straight unless I plug out the arduino cable. Any solution?

**Comment by VishalWrench** [comment]
yeah buddy i'm facing the same issue the frames are slow and the prediction and frames are out of sync . when i slowly move my camera around the track it predicts well. Solution is either to increase the frame rate or to reduce the car speed

**Comment by MyFirstRoboticProject** [comment]
Slowing the car will make the problem worse. My car is slow enough, but the serial output rate is just too fast. I need a way to reduce the rate of serial output (like three forwards per second or three forward rights per second). Also my camera is fine and the frame rate is satisfactory. The only problem is the serial output rate.

**Comment by MyFirstRoboticProject** [comment]
@VishalWrench BTW did you successfully train your car?

**Comment by MyFirstRoboticProject** [comment]
I found the solution to my problem. Closing thread

**Comment by VishalWrench** [comment]
How did u solved it??

**Comment by MyFirstRoboticProject** [comment]
Well, the output serial data would change instantaneously regardless how fast it was, so it didn't matter. And also if you want to achieve a greater accuracy for training make the driving path as narrow as possible.

**Comment by Devanshice020** [comment]
have you made your car by your self? @MyFirstRoboticProject

**Comment by MyFirstRoboticProject** [comment]
No. Used a normal rc car

**Comment by Devanshice020** [comment]
Have you code for cr's motor to control it's speed? @MyFirsrRoboticProject

**Comment by MyFirstRoboticProject** [comment]
Yup. Not an ideal solution though. I'm trying to find some other way to slow my car's speed (other than using a potentiometer or a resistor)

**Comment by Devanshice020** [comment]
I am having the same problem everything is working properly but car is very fast so it's not working properly.
If you find the solution plz let me know.
Thanks for your help

**Comment by MyFirstRoboticProject** [comment]
Ok
