### ISSUE TITLE
How to achieve low latency for video streaming for rc_driver.py?

### ISSUE THREAD

**Issue by MyFirstRoboticProject** [hamuchiwa/AutoRCCar#189]
I'm using mobile hotspot for connecting my raspberry pi and windows PC. Getting a 3 second delay. Anyway to solve it?

**Comment by MyFirstRoboticProject** [comment]
@hamachiwa 
Did you use stream.py or stream_fast.py for streaming in raspberry pi? I'm using stream_fast.py, so would using the stream.py fix the issue? Any advice would be appreciated

**Comment by MyFirstRoboticProject** [comment]
@DevanShice020 Is your streaming working fine rc_driver.py. I'm having a 3 sec delay

**Comment by hamuchiwa** [comment]
@MyFirstRoboticProject `stream.py` was used, the fast one was added later as an alternative. Both of them are taken from picamera documentation. 
Have you tried using a router instead? Maybe it's the hotspot causes the latency. . 
In case you haven't seen this [video](https://www.youtube.com/watch?v=KrvvmLEQk8o) yet, try to slow down your car as well. 
In the worst case if the delay cannot be improved, perhaps you can let the car move only after receiving an image, then car stops and waits for the next frame, then moves again.

**Comment by Devanshice020** [comment]
But sir how can we control stopping the image from receiving the pi camera
i mean it will continuous capture image to run on the track (rc._drive.py)
so how is it possible to stop the car , receive an image, and then allow
the car to run again @ hamuchiwa

**Comment by hamuchiwa** [comment]
@Devanshice020 We are not stopping streaming, we could stop the car after each move and let it wait until next frame. Adding `self.rc_car.stop()` after `self.rc_car.steer(prediction)`. Give it a try and hope it could easy the high delay issue.

**Comment by MyFirstRoboticProject** [comment]
@hamuchiwa
Well I'll give that a try. Thanks! Also my car needs three AA batteries for power so would replacing one of the AA batteries with a simple copper wire do the trick? It would reduce the effective voltage from 4.5 V to 3 V so the car should slow down. Will it work or would it harm the car?

**Comment by Devanshice020** [comment]
@hamuchiwa it worked.
Is it possible : i have more powered car rock crawler 1:18 and i did the same as you mentioned but my car did not moved an inch .. so what do you think might be the problem? Does the power of the car has something to do with the car not moving forward?

**Comment by hamuchiwa** [comment]
@Devanshice020 @MyFirstRoboticProject Be experimental may help...? For example, add some delay between steer and stop, if the car moves then it's the newly added line, if not, it's the car itself.

**Comment by Devanshice020** [comment]
how to give delay? @hamuchiwa 
Thanks in advance Sir

**Comment by VishalWrench** [comment]
import time
time.sleep(time in sec)

**Comment by MyFirstRoboticProject** [comment]
@Devanshice020
Did the battery method work?

**Comment by Devanshice020** [comment]
Actually my car has rechargeable lithium battery so this method will not work for that

**Comment by Devanshice020** [comment]
You can try this it worked for me but after that car speed will be very low but my objective for detecting lane for forward, left and right
https://github.com/hamuchiwa/AutoRCCar/issues/189#issuecomment-480295132
