### ISSUE TITLE
pygame

### ISSUE THREAD

**Issue by gokselaydogdu** [hamuchiwa/AutoRCCar#19]
Hello,
I have a question about pygame. Why did you use pygame in this project?

**Comment by isrugeek** [comment]
well, as the method is Supervised  Machine learning it needs Train Data as well as label So as Py Game  is a cross-platform set of Python modules designed for Games with Keyboard Support libraries, we can use our keyBoard Arrows to Drive our Car ( For training purpose ) . as this point we save those Arrays ( arrow driving methods) as a label. for better understanding . Read [More about Py GAME](https://www.pygame.org/docs/)
