### ISSUE TITLE
Broken pipe error 

### ISSUE THREAD

**Issue by Revanth2110** [hamuchiwa/AutoRCCar#190]
Hello there,
While i was running rc_driver.py code on my laptop and stream_client.py and ultrasonicsensor_client.py on raspberrry pi, i was  getting ultrosonic data but i was not able to get data from stream_client.py. Instead i was getting an error which is broken pipe error for stream_client.py.
**//**Error on pi:****
traceback (most recent call last): 
file stream client.py, line 30, in <module> 
connection.close() 
file /usr/lib/python2.7/socket.py, line 283, in close
 self.flush() 
file /usr/lib/python2.7/socket.py, line 307, in flush self._sock.sendall(view[write_offset:write_offset+buffer_size]) 
socket.error: [errno 32] broken pipe

**Comment by SaiSurya9999** [comment]
This problem is due to delay of server...
whenever the data is sent from client the server should be in listening mode if not broken pipe error arises..
To solve this increase the sleep time in client program after every measurement..

**Comment by codeskul** [comment]
@SaiSurya9999  i increased sleep time in ultrasonic_client.py file but it show me broken pipe error after few seconds
