### ISSUE TITLE
model.py

### ISSUE THREAD

**Issue by PuriHa** [hamuchiwa/AutoRCCar#191]
@hamuchiwa file code **model.py** for what? and run code at what step?
Thank you for an answer

**Comment by Devanshice020** [comment]
model.py is used in rc_drive.py, rc_driver_nn_only.py to import saved model and use other controls @PuriHa

**Comment by hamuchiwa** [comment]
@PuriHa 
@Devanshice020 has answered your question, also go through `readme` if that helps.
