### ISSUE TITLE
please help - Testing the car after training 

### ISSUE THREAD

**Issue by Sirajabudabe** [hamuchiwa/AutoRCCar#192]
after i finish training i run rc_driver_nn_only.py , the car stuck on forward and left only even tho the prediction of the neural network is right or forward !!!!!!
The prediction is true but the action is wrong why ??

**Comment by kxrf97** [comment]
maybe u mess up with your arduino pin setting

**Comment by harshithdayananda** [comment]
@hamuchiwa need help, after training and running rc_driver_nn_only the car is going forward and left only.
