### ISSUE TITLE
car model

### ISSUE THREAD

**Issue by arunph** [hamuchiwa/AutoRCCar#193]
which car you had bought.can u send me the link to buy the same car.

**Comment by TejasSaralaya** [comment]
It's better that  you design your own car with the Motor speed 60 rpm

**Comment by arunph** [comment]
but how it is possible to connect four direction pins corresponding to rc and aurdino

**Comment by hamuchiwa** [comment]
@arunph The link probably is gone by now, I just bought a simple rc car toy on Amazon. Since you have noticed #164, I'm closing this issue.
