### ISSUE TITLE
Issue regarding training of rc car

### ISSUE THREAD

**Issue by TejasSaralaya** [hamuchiwa/AutoRCCar#195]
1) I have made a straight track and trained my Rc car in that track....but when I run rc_driver.py the car moves in straight track but doesn't stop after the track ends.should it stop at the end of the track?
2) The video streaming is lagging while training the car. Is there any way to reduce the lag?
3)After running rc_driver.py the car doesn't move but terminal shows left command...what might be the issue.
It's urgent.....please do reply. 
Thank you @hamuchiwa

**Comment by hamuchiwa** [comment]
It doesn't stop, you need to exit the program to stop it. 
Take a look #187, #173 and #77, #189.
