### ISSUE TITLE
how training accuracy and validation accuracy is calculated?

### ISSUE THREAD

**Issue by Devanshice020** [hamuchiwa/AutoRCCar#200]
# evaluate on train data
train_accuracy = nn.evaluate(X_train, y_train)
print("Train accuracy: ", "{0:.2f}%".format(train_accuracy * 100))

# evaluate on validation data
validation_accuracy = nn.evaluate(X_valid, y_valid)
print("Validation accuracy: ", "{0:.2f}%".format(validation_accuracy * 100))

how this works??
plz reply ASAP..

**Comment by hamuchiwa** [comment]
@Devanshice020 They are calculated in the same way, accuracy = true/(true + false). Check `evaluate` function for detail.
