### ISSUE TITLE
onnection.write(stream.read()) File "/usr/lib/python3.5/socket.py", line 594, in write return self._sock.send(b)BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Shafaeit** [hamuchiwa/AutoRCCar#202]
https://stackoverflow.com/questions/55818107/multiple-client-in-socket-not-working-in-raspberry-pi-video-streaming

**Comment by hamuchiwa** [comment]
@Shafaeit It seems a python socket error. Just try to isolate the error, have you tested the connection using `stream_server_test.py`? If it still doesn't, create the conda environment as mentioned in readme, then try again.

**Comment by hamuchiwa** [comment]
@Shafaeit `rc_driver.py` has been updated.
