### ISSUE TITLE
rc_driver_nn_only.py runs fine but problem with rc_driver.py

### ISSUE THREAD

**Issue by tc2n** [hamuchiwa/AutoRCCar#203]
My `rc_driver_nn_only.py` file runs fine, but when I try to run `rc_driver.py` and run `stream_server.py` on the client I get broken pipe error on the client side and server command just terminates without giving any error. This error is generated only when I start `stream_server.py` on the client side.

**Comment by enigma0503** [comment]
I am also getting the same error(broken pipe error when I run the `stream_server.py`)

**Comment by codeskul** [comment]
I face same issue

**Comment by codeskul** [comment]
Only ultrasonic_client.py runs when I start stream_client.py it show me error

**Comment by codeskul** [comment]
![15564477916015266531347955756738](https://user-images.githubusercontent.com/41965052/56863075-9e825880-69cf-11e9-8f83-ced3d3e04afb.jpg)

**Comment by codeskul** [comment]
![15564480655361787959251118283671](https://user-images.githubusercontent.com/41965052/56863124-4435c780-69d0-11e9-8ccc-f1961d703d10.jpg)

**Comment by hamuchiwa** [comment]
@tc2n @codeskul See if this is what you encountered on the server side: #176, #185

**Comment by codeskul** [comment]
@hamuchiwa no sir it not work

**Comment by hamuchiwa** [comment]
@codeskul What's the error on the server side?

**Comment by codeskul** [comment]
When I start server side code rc_driver.py it don't show any error, in raspberry pi i start ultrasonic_client.py it sends sensor data well, as I start stream_client.py on raspberry pi it stop and show broken pip error on raspberry pi as shown above and at server side it shows system exit as shown above

**Comment by codeskul** [comment]
It stop server side execution when i start raspberry side stream_client.py

![error](https://user-images.githubusercontent.com/41965052/56866799-5ed16600-69fb-11e9-965c-1cd2a0a8b4c0.png)

**Comment by hamuchiwa** [comment]
@codeskul Have you tried running stream_client first or on linux? This project was only tested on Linux and Mac, it could the way of handling threads is different on windows.

**Comment by codeskul** [comment]
@hamuchiwa  ok i will try it on Linux and reply to you

**Comment by tc2n** [comment]
@hamuchiwa I face the same problem on Linux.

**Comment by tc2n** [comment]
I tried to remove the 'stop sign' detection part from the `rc_driver.py` file, then I was able to run `stream_server.py` file too, but still when I try to run `ultrasonic_stream` file I got Broken Pipe error with no error on Server Side (I am unable to run both `stream_server.py` and `ultrasonic_stream.py` simultaneously).

**Comment by hamuchiwa** [comment]
@tc2n @codeskul My mistake, forgot to put `self` before variables in last update. `rc_driver.py` has been updated and should be working now.

**Comment by ShwetaLalwani** [comment]
@tc2n Hi, is your car moving in the correct directions after running rc_driver_nn_only.py?

**Comment by tc2n** [comment]
@ShwetaLalwani When I run model_training on .npz file, sometimes it works fine. But sometimes when I again train the model on the same .npz file my car always moves in the same direction(Always right or Always forward).
