### ISSUE TITLE
SerialException: could not open port '/dev/tty.usbmodem1421': FileNotFoundError(2, 'The system cannot find the path specified.', None, 3)

### ISSUE THREAD

**Issue by introvertguy** [hamuchiwa/AutoRCCar#204]
I'm trying this project on Windows 10 and I've trained my model with 68% and above accuracy but I CAN'T DEPLOY the rc_driver.py because of the Serial exception error. I've my project demonstration tomorrow and I'm freaking out over this issue.. Please help out @hamuchiwa

**Comment by hamuchiwa** [comment]
@introvertguy Change the serial port to match your Windows one, line 42.
