### ISSUE TITLE
rc_driver executes with no error but laptop doesn't send any signal to Arduino

### ISSUE THREAD

**Issue by introvertguy** [hamuchiwa/AutoRCCar#205]
Stream test on Raspberry pi and rc_driver on computer executes without any error and the Camera module turns on as well. But I don't get any output onto the Arduino UNO. @hamuchiwa

**Comment by hamuchiwa** [comment]
@introvertguy Can you elaborate a bit more? No output in the console, or light is not blinking or something else?
