### ISSUE TITLE
关于收集训练数据

### ISSUE THREAD

**Issue by BreakerMark** [hamuchiwa/AutoRCCar#207]
您好，我发现收集训练数据这个文件里的一些问题，但是不知道如何解决，还希望您能够提供帮助。
训练的时候，同时按下前进和方向，这时如果只松开方向键继续按着前进键，小车就会停止并不会继续往前，我觉得应该是判断条件的那个一旦KEYUP就停车导致的，但不知道如何解决，您能提供一些帮助吗？谢谢。

**Comment by hamuchiwa** [comment]
@BreakerMark 收集数据的时候要点按，每点一下键盘收集一张图片，一直按着的话只收集一张。收集左右方向的时候可以这个样子：按住方向键不放，然后点按前进键，这样比一次按两个键要准确一点儿。

**Comment by BreakerMark** [comment]
哦，多谢多谢，怪不得我发现弄了好久结果没收集到几帧。
