### ISSUE TITLE
Haar Cascade Classifier 

### ISSUE THREAD

**Issue by mmtaksuu** [hamuchiwa/AutoRCCar#209]
Hi,
I wonder how many photos did you use for your classifier?
What did you choose for sample width and height?
Did you use any other features for your classifier? 
Thanks for your help...

**Comment by hamuchiwa** [comment]
@mmtaksuu Don't quite remember, but definitely below 100, perhaps 40 to 60 images. Dimension is small, 25x25 for stop sign, 25x45 for traffic light. I followed this [tutorial](https://coding-robin.de/2013/07/22/train-your-own-opencv-haar-classifier.html).
