### ISSUE TITLE
*Urgent* Issue with port

### ISSUE THREAD

**Issue by nikhilabhi** [hamuchiwa/AutoRCCar#210]
File "C:\Users\Admin\PycharmProjects\qtpi_rc car\venv\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM34': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

I am getting this issue when i run python collecting training data script. Can anyone solve this please

**Comment by hamuchiwa** [comment]
@nikhilabhi It says the could not open port, can you verify the COM port you are using on windows?
