### ISSUE TITLE
测距程序相机参数中的角度该如何测量？

### ISSUE THREAD

**Issue by revox0x** [hamuchiwa/AutoRCCar#212]
就是这行代码中的参数`self.alpha = 8.0 * math.pi / 180    # degree measured manually`

**Comment by hamuchiwa** [comment]
@revox0x 拿量角器测的，光轴和水平线的夹角。我找的那篇文献好像链接失效了，不过你可以搜一下“车辆单目测距”，搞不好还有新方法来着。

**Comment by revox0x** [comment]
感谢您的回复，但是我还是不太明白具体该如何去测量，能麻烦您详细说明一下吗。

**Comment by hamuchiwa** [comment]
@revox0x 找着两篇文章，几何模型是类似的
[基于单目视觉的前方车辆检测与测距](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwj83ZDs1rTiAhVEhOAKHY5_CHgQFjABegQIBRAC&url=http%3A%2F%2Fwww.ecice06.com%2FEN%2Farticle%2FdownloadArticleFile.do%3FattachType%3DPDF%26id%3D27545&usg=AOvVaw3XjNH-E7uD_HxcjQGnEVKw)
[基于单目视觉的前方车辆探测方法](http://read.pudn.com/downloads122/doc/project/519187/桌面/基于单目视觉的前方车辆探测方法.pdf)

**Comment by revox0x** [comment]
感谢！对我帮助很大。
