### ISSUE TITLE
关于红绿灯状态判断的问题

### ISSUE THREAD

**Issue by revox0x** [hamuchiwa/AutoRCCar#214]
在下面的程序中
![屏幕快照 2019-05-25 下午5 56 53](https://user-images.githubusercontent.com/48538908/58367833-83473200-7f16-11e9-84ef-5a84f5afa8ff.png)
我理解的是`if 1.0 / 8 * (height - 30) < maxLoc[1] < 4.0 / 8 * (height - 30):`和
` elif 5.5 / 8 * (height - 30) < maxLoc[1] < height - 30:`是通过maxLoc[1]表示的最亮点的垂直方向的位置来判断红灯还是绿灯亮起，但是我不理解判断的条件是如何产生的，也就是说它为什么可以写成这样？

**Comment by hamuchiwa** [comment]
@revox0x 简单说是人为加上去的。那个红绿灯是淘宝上买的，红灯在上绿灯在下，所以亮点在大致上半部分就是红灯，下半部分那就是绿灯了。
等于是走了个捷径，当然你也可以用颜色来判断，读取进来的图像要是彩色的，然后再定义红颜色和绿颜色的区间。

**Comment by revox0x** [comment]
感谢您的回复，我明白了。
