### ISSUE TITLE
如何高效处理用于训练haar分类器的阳极样本图片？

### ISSUE THREAD

**Issue by revox0x** [hamuchiwa/AutoRCCar#215]
我想训练一个分类器，但在处理阳极样本的图片上遇到了困难，通过手机采集图像之后，我不知道该如何精确地将目标样本按照25x45的像素比例裁剪出来，请问有高效的方法可以解决这个问题吗？

**Comment by hamuchiwa** [comment]
裁剪的时候固定好长宽比，分辨率先不用管，全部裁剪完之后，可以用photoshop批处理或者写几行代码改成统一的分辨率

在 2019年5月26日，15:15，revox0x <notifications@github.com<mailto:notifications@github.com>> 写道：


我想训练一个分类器，但在处理阳极样本的图片上遇到了困难，通过手机采集图像之后，我不知道该如何精确地将目标样本按照25x45的像素比例裁剪出来，请问有高效的方法可以解决这个问题吗？

**Comment by revox0x** [comment]
感谢您的回复，我知道该怎么做了。
