### ISSUE TITLE
collect_training_data Error

### ISSUE THREAD

**Issue by annak1n** [hamuchiwa/AutoRCCar#218]
My Step:
1) Run on PC: collect_training_data.py
2) Run on RPi: stream_client.py
Then i get this error.
Error Screen Shot:
http://prntscr.com/o0oc2e
I not have RC Controller. Can i use Keyboard on my PC for Control Car ?
How i can fix this error ?

**Comment by harshithdayananda** [comment]
@annak1n change your serial port to the one you have connected the arduino
