### ISSUE TITLE
运行collect_training_data.py问题

### ISSUE THREAD

**Issue by lizhongdjjy** [hamuchiwa/AutoRCCar#224]
你好，运行采集数据程序时，报错：
QObject::moveToThread: Current thread (0x1cd6540) is not the object's thread (0x1e47bc0).
Cannot move to target thread (0x1cd6540)

Fatal Python error: PyEval_SaveThread: NULL tstate
已放弃 (核心已转储)

python2.7 和python3 都有这个错误

**Comment by hamuchiwa** [comment]
@lizhongdjjy 之前没遇到过这个问题，我大概搜了一下，有说是关于OpenCV或者是pyqt的问题。你用的是Ubuntu还是mac，找个时间我也试一下看能不能重复一样的错误。

**Comment by hamuchiwa** [comment]
@lizhongdjjy 我试了一下，在Ubuntu的虚拟机重新构建的conda环境，默认下载的python版本是3.7.4，OpenCV是4.1.1，运行正常没报错呀。
