### ISSUE TITLE
Trouble with collect_training_data.py and stream_client.py

### ISSUE THREAD

**Issue by zodiacrx** [hamuchiwa/AutoRCCar#225]
Greetings, Sir
i use my school wi-fi (host, raspberrypi) and i have error message when doing collect_training_data and stream_client , collet_training_data is work well but when i run stream_client.py and i got error message 
File "stream_client.py", line 11, in <module>

    client_socket.connect(('172.29.127.44', 4000))

  File "/usr/lib/python2.7/socket.py", line 228, in meth

    return getattr(self._sock,name)(*args)

socket.error: [Errno 111] Connection refused

host address is school wi-fi address,and i use port 4000
any idea solve this problem

**Comment by hamuchiwa** [comment]
@zodiacrx The error says "Connection refused", if the ip and port number match the ones on the server side, try a different port then.
