### ISSUE TITLE
Can I do this without remotecontroller?

### ISSUE THREAD

**Issue by zodiacrx** [hamuchiwa/AutoRCCar#226]
@hamuchiwa 
Hi, Sir I really like this project and I make my own RC car
with 2 DC Motor and L298N motordriver all .py code works well 
but, i have one thing in mind i don't have any remote controller so i only use keyboard to RC_keyboard_control, collect_training_data training with youtube driving video
but, problem is rc_driver.py i don't have remotecontroller so my arduino(connect with DC motor and motor driver) connect with computer 
rc_car = RCControl("/dev/ttyACM1") 
serial.port of arduino but i can't drive because my arduino is connected with computer 
any solution? it can be great help to me suggest a solution

**Comment by hamuchiwa** [comment]
@zodiacrx Quick answer is yes. This is an old project, personally I haven't tried not using remote controller, but I believe there are people who have successfully done similar projects using raspberry pi only. You can have a look at these two: #16 and #199. First one is the discussion of how to work with pi only, second contains a few urls of very inspiring projects. 
Hope this helps. Good luck~!
