### ISSUE TITLE
Neural network weird behavior!!!

### ISSUE THREAD

**Issue by Sirajabudabe** [hamuchiwa/AutoRCCar#227]
in training even when i don't use reverse button .... i get some predictions of reverse 
training accuracy is to low !! how to reduce NN output to be just (Forward-right-left)???and what is the best attributes for good accuracy ?  
any ideas ? @hamuchiwa

**Comment by hamuchiwa** [comment]
@Sirajabudabe Please see #173 and #187 for help, certainly reverse can be removed (it's not used anyway), you need to modify the label array size wherever you see that in the code.

**Comment by Sirajabudabe** [comment]
@hamuchiwa  thanks .. i just want to ask about the training (collecting data ) should i do the "right-left , forward " in separate npz file  or i collect data over hole track (all directions at once )?
does it effect the training accuracy ?
