### ISSUE TITLE
collecting data 

### ISSUE THREAD

**Issue by Sirajabudabe** [hamuchiwa/AutoRCCar#229]
@hamuchiwa i just want to ask about the training (collecting data ) should i do the "right-left , forward " in separate npz file or i collect data over hole track (all directions at once )?
does it effect the training accuracy ?

**Comment by hamuchiwa** [comment]
@Sirajabudabe You can just drive along the track multiple times, there is no need to separate the directions. After each run, a npz file will be generated in the training_data folder. In training, all files in that folder will be loaded at once.
