### ISSUE TITLE
Anybody implemented in Windows without Remote control?

### ISSUE THREAD

**Issue by kartikJ-9** [hamuchiwa/AutoRCCar#230]
Shall I run all my scripts in a virtual machine?

I get a pygame black screen prompt but when I type a character from keyboard, Arduino does receive it, but motor does not rotate accordingly. What might be the reason for this?

**Comment by kartikJ-9** [comment]
Also when I run rc_control.py, a black pygame screen appears. But, the Arduino prompt says that the COM7 is busy, and that is because python script is utilising COM7.

**Comment by hamuchiwa** [comment]
@kartikJ-9 If you can, run this project on Linux or Mac, Windows is not tested, but there are people managed to work with this project on Windows. 
The small black pygame window is normal, it's for capturing keypress. Not sure if there is a better way for capturing keypress without opening a pygame window. 
If Arduino does receive keyboard commands, maybe check the connection between Arduino and the controller? (#164)
