### ISSUE TITLE
Remote control problem

### ISSUE THREAD

**Issue by Sirajabudabe** [hamuchiwa/AutoRCCar#231]
I changed the car for some technical problems , the push buttons in the new car are active high 
not like what @hamuchiwa  used am having a lot of troubles trying to control the car mostly in hardware and arduino code !!!! did any one tried different arduino code ?
help please

**Comment by SaiSurya9999** [comment]
@Sirajbudabe use delay() function in audrino code to control speed of car..
My car YouTube link
https://youtu.be/TrXVGF6cBBU

**Comment by Sirajabudabe** [comment]
@SaiSurya9999  how much delay you used ???
could you contact me on serajabudaber@gmail.com

**Comment by SaiSurya9999** [comment]
@Sirajabudabe  I have mailed you the audrino code i modified with delay functions check it out..!!!
