### ISSUE TITLE
car don't stop 

### ISSUE THREAD

**Issue by Sirajabudabe** [hamuchiwa/AutoRCCar#233]
am having a problem with "rc_driver.py" when ultrasonic gives a stop signal or the stop sign put stop_flag true it don't wait until the obstacle is removed  !!!!
i also noticed that there is no wait function in the code after obstacle detection ?!!!!
@hamuchiwa  any ideas why???

**Comment by SaiSurya9999** [comment]
I have given you my drive programs through mail @Sirajabudabe  check it out.

**Comment by Yoganandhan01** [comment]
@SaiSurya9999 @Sirajabudabe 
I'm having the same problem in "rc_driver.py".  My car also won't stop when the object was detected.? 
Can You help me with this problem..!
