### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by athenluffy** [hamuchiwa/AutoRCCar#234]
the streaming server_test program for computer is not working. It is Showing connection refused 
![server](https://user-images.githubusercontent.com/31587653/69532309-842b5000-0f9b-11ea-9e4b-72909675d7e5.png)

**Comment by hamuchiwa** [comment]
@athenluffy Change the ip address in both client (`stream_client.py`) and server (`stream_server_test.py`) files to match your. See #144 if that helps.
