### ISSUE TITLE
Plz share schematic diagram of arduino to raspberry pi

### ISSUE THREAD

**Issue by habib700** [hamuchiwa/AutoRCCar#237]
Sir, 
Inspired by this aiticle: Drive a Lamborghini With Your Keyboard link is not working, plz share a clear schematic of connections with Arduino and Raspberry.
Thanks.

**Comment by hamuchiwa** [comment]
@habib700 Please see #164 and #124.

**Comment by abhijeet1813** [comment]
hello sir !! I am also trying to build an autonomous car but the biggest
problem in front of me is hardware setup will you please help me with
respect to that. It will be really helpful. Thank You!!

**Comment by Yoganandhan01** [comment]
please share the schematic for arduino to raspberry pi
