### ISSUE TITLE
Neural Network Training

### ISSUE THREAD

**Issue by nandhukrishnan** [hamuchiwa/AutoRCCar#240]
@hamuchiwa

1. What are the minimum system requirements for the training of this Neural Network?

2. How to implement the same project using Convolutional Neural Network? Can you please share 
    the modified files `model.py` and `model_training.py`. Thanks in advance :)
    mail id: [nandhukrishnan96@gmail.com](url)

3. Please suggest a power bank with sufficient capacity and minimum weight to use with     
    raspberry pi?

**Comment by hamuchiwa** [comment]
@nandhukrishnan Hi, the model is trained on computer, so your laptop is sufficient to train the model, certainly if your model is more complex and you have more data, it takes longer. There are no modified files, but please take a look at #173. As long as it not too heavy for your rc car, any usb power supply should work.
