### ISSUE TITLE
How to connect raspberry pi to Rc control unit

### ISSUE THREAD

**Issue by Yoganandhan01** [hamuchiwa/AutoRCCar#241]
how to connect the motor controller board with raspberry pi.  is there any schematic is available

**Comment by arunph** [comment]
Actually you need to connect aurdino with controller not raspberry pi. 
Thanks

**Comment by Yoganandhan01** [comment]
Thanks for your reply Arun


Yoganandhan A

**Comment by 9salman7** [comment]
@arunph can you help with my question #242 as well please?
