### ISSUE TITLE
Sending predictions to the Arduino

### ISSUE THREAD

**Issue by 9salman7** [hamuchiwa/AutoRCCar#242]
Hi @hamuchiwa , you mentioned that the predictions are the sent to the Arduino for RC car control. How is this done? As far as I understand, the Arduino is only connected to the remote controller. How exactly is the data sent to the Arduino without connecting it to the RPi or the Computer?

Thanks for your help!

**Comment by arunph** [comment]
No need to connect raspberry pi to Rc control unit. You can connect Rc control with Arduino. Since raspberry pi will  send the and receive pi camera and ultrasonic sensor data from and to the computer which in further sends Direction instructions to Ardunio to control the Car.

**Comment by 9salman7** [comment]
How exactly does the computer send instructions to the Arduino? @arunph

**Comment by arunph** [comment]
kindly go through this link https://zhengludwig.wordpress.com/projects/self-driving-rc-car/

**Comment by 9salman7** [comment]
I did go through it, it mentions that the Arduino is connected to the computer via USB. I'm still unsure how the connection is done remotely.

**Comment by arunph** [comment]
As the per the project is concern,raspberry pi need to be powered up and then connect its wifi to router or mobile hotspot and then connect your computer wifi  to same network which you have used to connect raspberry pi.Both should lie in the same network.
