### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by reddy9698** [hamuchiwa/AutoRCCar#244]
Hi, Hamuchiwa 
I'm getting the following error while running the ultrasonic_client.py

ValueError: could not convert string to float: b'14.59320783615112314.568674564361572'.

I tried everything from previous issues and not getting an answer.

**Comment by hamuchiwa** [comment]
@reddy9698 Try change line 52 in `ultrasonic_client.py` to `client_socket.send(str(distance).encode('utf-8'))`.  File has been updated in repository . See #132.

**Comment by reddy9698** [comment]
yeah i have done that but still iam getting the same error
