### ISSUE TITLE
Stop sign detection

### ISSUE THREAD

**Issue by salman-ind** [hamuchiwa/AutoRCCar#245]
Hi @hamuchiwa , can you please explain why you have used the following logic for detecting the stop signs?

`# stop sign
if width / height == 1:
      cv2.putText(image, 'STOP', (x_pos, y_pos - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)`

why does width/height == 1 mean that the object is a stop sign? For reference, those two variables are returned from the detectMultiScale function from OpenCV

**Comment by maazmmd** [comment]
Am also stuck here, How to stop the car using a stop sign

**Comment by hamuchiwa** [comment]
@9salman7 The bounding box of stop sign in this project is a square, so if width == height, it's a stop sign.

**Comment by salman-ind** [comment]
> @9salman7 The bounding box of stop sign in this project is a square, so if width == height, it's a stop sign.

Thank you for the reply! I appreciate it

We have completed everything apart from the traffic signal detection (will finish that soon) thanks to your wonderful repository. Thank you so much, @hamuchiwa !

Have a look - https://drive.google.com/open?id=10Z7oCw4XpBe3b9kgd6YishomECpyB6iY

**Comment by Yoganandhan01** [comment]
Hi Salman. I have also followed those steps but my car only goes on the straight that does not follow the lane. How can i solve the problem..?

**Comment by Yoganandhan01** [comment]
@9salman7 can you help me.?

**Comment by salman-ind** [comment]
> Hi Salman. I have also followed those steps but my car only goes on the straight that does not follow the lane. How can i solve the problem..?

Hello @Yoganandhan01. Are you following the OpenCV neural network model? I did that too and my car was also moving along just one direction. 
I'd suggest you to use a Keras neural network model. It works perfectly for me.

**Comment by Yoganandhan01** [comment]
How can I implement Keras neural network into it.? Can you tell me some
examples.?
Yoganandhan A

**Comment by salman-ind** [comment]
You can refer to this Jupyter notebook:
https://github.com/9salman7/self-driving-car2/blob/master/kerasInfernus.ipynb

After training, you can load the model into your program to predict the directions

**Comment by Yoganandhan01** [comment]
Thanks Salman..

Yoganandhan A

**Comment by denisrexhepi** [comment]
Did the Keras model work?

**Comment by Chinmay922** [comment]
I want to work on the same model but on MATLAB is it possible?
