### ISSUE TITLE
Why Every Pin is Low in arduino code

### ISSUE THREAD

**Issue by moizmushtaq** [hamuchiwa/AutoRCCar#247]
Hi Sir. I found some difficulty while understanding the code of arduino. E.g When u receive forward command from python program. Then the forward pin should be HIGH. Why it is all LOW in functions. Doesn’t it that mean to off the pin. If it is LOW then how can car go forward...
 You answer will be appreciated sir

**Comment by ShahirZain** [comment]
yes you are right forward pin should be high i think it is a silly mistake

**Comment by Manou60xs** [comment]
Hi bro , Please can you tell me which rc car you choosed 
and tell how did you do to connect arduino to Rc car control unit.
