### ISSUE TITLE
New self driving car on the block?

### ISSUE THREAD

**Issue by aleonnet** [hamuchiwa/AutoRCCar#26]
Hi @hamuchiwa great job!
Do you think is it really possible to build this project or it's a decoy?  https://www.youtube.com/watch?v=9QRTg-4q634
Interesting the guy claims to use RPi only (no PC). 
Thanks

**Comment by hamuchiwa** [comment]
Actually I came across this video a few days ago when I was searching TensorFlow. Wish the author can give more detail and open source his project. 
But anyway, TensorFlow could be the next big thing, in my opinion.
