### ISSUE TITLE
Getting error in ULTRASONIC_CLINT.py 

### ISSUE THREAD

**Issue by darshansm** [hamuchiwa/AutoRCCar#28]
Traceback (most recent call last):
  File "/home/pi/Downloads/AutoRCCar-master/raspberryPi/ultrasonic_client.py", line 52, in <module>
    distance = measure()
  File "/home/pi/Downloads/AutoRCCar-master/raspberryPi/ultrasonic_client.py", line 31, in measure
    elapsed = stop-start
UnboundLocalError: local variable 'stop' referenced before assignment

**Comment by darshansm** [comment]
Traceback (most recent call last):
  File "/home/pi/Downloads/AutoRCCar-master/raspberryPi/ultrasonic_client.py", line 52, in <module>
    distance = measure()
  File "/home/pi/Downloads/AutoRCCar-master/raspberryPi/ultrasonic_client.py", line 31, in measure
    elapsed = stop-start
UnboundLocalError: local variable 'stop' referenced before assignment

**Comment by hamuchiwa** [comment]
It seems the loop is not executed: while GPIO.input(GPIO_ECHO)==1
Do you get any input from GPIO pin?

**Comment by darshansm** [comment]
i am getting distance.......i can see "obstacle in front" message in computer. once i remove obstacle, i am getting that error

**Comment by hamuchiwa** [comment]
Have you tried to declare variables at the beginning of the measure() function:
start, stop = 0, 0
I wonder what would happen.

**Comment by darshansm** [comment]
no...i ll try once
i didn't change any thing in program except IP

**Comment by darshansm** [comment]
i tried....getting same error

**Comment by chandrakant-github** [comment]
@hamuchiwa how to train the car for obstacle ahead how ultrasonic data is tought  ??

can you explain pls

**Comment by chandrakant-github** [comment]
@hamuchiwa  can you provide me code through which you have taken cascade_xml 

for stop and traffic sign

**Comment by hamuchiwa** [comment]
@chandrakant-github Hi, ultrasonic sensor just measures the distance, if the distance is below some threshold, you make the car stop. Regarding your second question, are you referring to how to train cascade classier? I followed a great tutorial, link is on project home page, or in your another thread.

**Comment by chandrakant-github** [comment]
@hamuchiwa thank you so much  for great help
