### ISSUE TITLE
Version OpenCV

### ISSUE THREAD

**Issue by MihaiSandor** [hamuchiwa/AutoRCCar#33]
Hello, what do you use version of opencv? And please share your schema for connections raspberry pi and arduino (sensors). Thank you so much. It”s most important version opencv.

**Comment by hamuchiwa** [comment]
OpenCV: 2.4.10.1 

Connect ultrasonic sensor to Raspberry pi:
![hc-sr04](https://cloud.githubusercontent.com/assets/9021941/25813219/b5c44db2-33e6-11e7-8e63-a79463f11bd5.jpg)

**Comment by MihaiSandor** [comment]
Thank you so much!

**Comment by MihaiSandor** [comment]
Can you please give me a schema for Arduino and controller?

**Comment by hamuchiwa** [comment]
It really depends on your controller, here is mine:
![img_9006](https://cloud.githubusercontent.com/assets/9021941/25819931/89d70854-33fd-11e7-9b23-dfd9b55424d3.jpg)

**Comment by MihaiSandor** [comment]
Is like yours. In which pins the threads are inserted? In Arduino of course.

**Comment by hamuchiwa** [comment]
It doesn't matter that much what pins you selects, in m case I have 6, 7, 9 10 (simply because 8 is broken). I originally planed to power the controller through Arduino, black wire connects to negative. It's not used, you can ignore that black wire.
