### ISSUE TITLE
Delay Response of Arduino to control motors Plz Help

### ISSUE THREAD

**Issue by AiBuddy** [hamuchiwa/AutoRCCar#47]
I am using arduino and motor driver l238N , while executing collect training data file i am facing problem of delay response from arduino. The lights of arduino TX/RX are on continuously while executing code. Motors are moving about after 5 to 8 seconds of key press. please help me as quick as possilble.. thank you in advance @hamuchiwa

**Comment by hamuchiwa** [comment]
Hi, I'm not familiar with motor shield, do you see any delay using the rc_control_test.py file?

**Comment by AiBuddy** [comment]
thank you for reply . i am back to remote control now. i dont use motor driver shield anymore . but i have another problem now. I cant control my rc car if i plug both right and left buttons. Once i remove any left or right wire from arduino . its works like charm. why is it happening? is it because my remote control architecture may be different from yours?

**Comment by AiBuddy** [comment]
everything is working now but i am facing delay in training file. when i hit forward key my car is moving after some seconds. any solution ? @hamuchiwa

**Comment by AiBuddy** [comment]
i fix it by myself. one more question. how big should be my npz file for test? how much should i train my car. i have no curve path. i am only training it on straight path. will it effect automation?

**Comment by hamuchiwa** [comment]
If it's just a straight line, then you don't need much data. You can try it out to see how many images is good enough.

**Comment by xmoose** [comment]
hi guys ,@Aibuddy how did you manage to get rid of the delay?even i am having 2..3s delay..any help appreciated

**Comment by AiBuddy** [comment]
@xmoose  try to put your remote antenna at 90 degree

**Comment by AiBuddy** [comment]
@xmoose check if there is any unwanted input in arduino code

**Comment by xmoose** [comment]
@AiBuddy did you complete this project? i'm having issues running the RC_driver.py did you run it?

**Comment by AiBuddy** [comment]
what issues you are having in rc_driver.py . post errors or issues @xmoose

**Comment by M-Salman1337** [comment]
hey AiBuddy, do u know how to interface arduino controls for the car into python program?
