### ISSUE TITLE
Training model  and accuracy.

### ISSUE THREAD

**Issue by IsmoilovMuhriddin** [hamuchiwa/AutoRCCar#57]
So far I have managed to stream video to my computer and taking training data by saving them in .npz file. (Still, I have more than 4000 pics and labels- training data)
train.shape - (1762, 38400)
train_label.shape - (1762, 4)

But now I have a problem with a model which returns as output always the same number: all 0s,1s or 2s.
Here I used two models- from opencv3: cv2.ml.ANN_MLP_create() and from Tensorflow.

**Question** 

- How to reach the best accuracy?

- Can you test my code on your training data, so if its accuracy is high enough my training data will be trash and I should collect absolutely different training data?

mlp_training.py
```
import cv2
import numpy as np
import glob
import sys
from sklearn.model_selection import train_test_split
import tensorflow as tf
import keras.backend
from keras.layers import Flatten, Dense, Dropout, Lambda, Convolution2D, Cropping2D, Conv2D, Conv1D, Reshape
from keras.callbacks import EarlyStopping
from keras.models import Sequential
import matplotlib.pyplot as plt


print 'Loading training data...'
e0 = cv2.getTickCount()

# load training data
image_array = np.zeros((1, 38400))
label_array = np.zeros((1, 4), 'float')
training_data = glob.glob('training_data/*.npz')



# if no data, exit
if not training_data:
    print "No training data in directory, exit"
    sys.exit()

for single_npz in training_data:
    with np.load(single_npz) as data:
        print data.files
        train_temp = data['train']
        train_labels_temp = data['train_labels']
        print train_temp.shape
        print train_labels_temp.shape
    image_array = np.vstack((image_array, train_temp))
    label_array = np.vstack((label_array, train_labels_temp))

train = image_array[1:, :]
train_labels = label_array[1:, :]

# train test split, 7:3
train_X, test_X, train_y, test_y = train_test_split(train, train_labels, test_size=0.3)

print train.shape
print train_labels.shape

show_images = False
export_images = False
should_train = True
use_tensorflow = True

def show_image(sample, delay=200):
    sample = sample.reshape((120, 320)).astype(np.uint8)
    cv2.imshow('image', sample)
    cv2.waitKey(delay=delay)


if show_images:
    for sample in train:
        show_image(sample)

if export_images:
    for i, sample in enumerate(train):
        sample = sample.reshape((120, 320)).astype(np.uint8)
        cv2.imwrite('export/' + str(i) + '.png', sample)


if not should_train:
    exit('should not train')

e00 = cv2.getTickCount()
time0 = (e00 - e0)/ cv2.getTickFrequency()
print 'Loading image duration:', time0


# set start time
e1 = cv2.getTickCount()


if use_tensorflow:
    #create Tensorflow model
    model = Sequential([
        Reshape((320, 120), input_shape=(train[0].shape)),
        # Conv2D(24, kernel_size=(3, 3), strides=(3, 3), activation='relu', input_shape=input_shape),
        Conv1D(24, kernel_size=3, strides=3, activation='relu'),
        Dropout(0.5),
        # Conv2D(36, kernel_size=(3, 3), strides=(3, 3), activation='relu'),
        Conv1D(32, kernel_size=3, strides=3, activation='relu'),
        Dropout(0.5),
        Conv1D(48, kernel_size=3, strides=3, activation='relu'),
        Flatten(),
        Dense(4)
    ])

    model.compile(loss='mse', optimizer='adam')

    early_stopping = EarlyStopping(monitor='val_loss', patience=2)
    history = model.fit(train_X, train_y, nb_epoch=120, validation_split=0.2, callbacks=[early_stopping])

    model.save('model.h5')

    resp = model.predict(test_X)
    prediction = resp.argmax(-1)
    print 'Prediction:', prediction
    true_labels = test_y.argmax(-1)
    print 'True labels:', true_labels

    print 'Testing...'
    train_rate = np.mean(prediction == true_labels)
    print 'Train rate: %f:' % (train_rate * 100)


    plt.plot(history.history['loss'])
    plt.plot(history.history['val_loss'])
    plt.title('model mean squared error loss')
    plt.ylabel('mean squared error loss')
    plt.xlabel('epoch')
    plt.legend(['training set', 'validation set'], loc='upper right')
    plt.savefig('history.png')

else:
    #create MLP
    layer_sizes = np.int32([38400, 32, 4])
    model = cv2.ml.ANN_MLP_create()
    model.setLayerSizes(layer_sizes)
    model.setTrainMethod(cv2.ml.ANN_MLP_BACKPROP)
    model.setBackpropMomentumScale(0.0)
    model.setBackpropWeightScale(0.001)
    model.setTermCriteria((cv2.TERM_CRITERIA_COUNT | cv2.TERM_CRITERIA_EPS, 500, 0.0001))
    model.setActivationFunction(cv2.ml.ANN_MLP_SIGMOID_SYM, 2, 1)

    criteria = (cv2.TERM_CRITERIA_COUNT | cv2.TERM_CRITERIA_EPS, 500, 0.0001)
    criteria2 = (cv2.TERM_CRITERIA_COUNT, 100, 0.001)

    params = dict(term_crit = criteria,
    train_method = cv2.ml.ANN_MLP_BACKPROP,
    bp_dw_scale = 0.001,
    bp_moment_scale = 0.0 )

    print 'Training MLP ...'
    num_iter = model.train(np.float32(train_X), cv2.ml.ROW_SAMPLE, np.float32(train_y))


    # set end time
    e2 = cv2.getTickCount()
    time = (e2 - e1)/cv2.getTickFrequency()
    print 'Training duration:', time
    #print 'Ran for %d iterations' % num_iter

    model.save('mlp_xml/mlp.xml')

    print 'Ran for %d iterations' % num_iter

    ret, resp = model.predict(test_X)
    prediction = resp.argmax(-1)
    print 'Prediction:', prediction
    true_labels = test_y.argmax(-1)
    print 'True labels:', true_labels

    print 'Testing...'
    train_rate = np.mean(prediction == true_labels)
    print 'Train rate: %f:' % (train_rate * 100)



# try to avoid 'NoneType' object has no attribute 'TF_DeleteStatus' error
keras.backend.clear_session()
```

output with tensorflow:
```
Prediction: [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2]
True labels: [0 2 1 0 2 0 0 2 2 2 2 2 0 0 2 0 2 2 2 2 2 0 2 0 2 2 2 1 0 2 2 2 2 2 2 0 0
 2 2 2 1 0 0 2 0 2 2 2 1 2 2 1 0 1 2 2 1 2 0 2 2 0 0 2 2 2 1 2 0 1 1 0 2 2
 1 0 2 1 2 2 1 2 2 2 1 2 0 2 0 2 2 0 0 2 2 2 1 2 2 2 2 2 2 2 1 1 2 0 2 2 2
 2 2 2 2 2 0 2 2 2 2 2 0 1 0 0 0 2 2 0 2 0 2 2 2 2 2 0 0 2 2 2 2 2 2 2 0 2
 2 2 2 0 2 2 2 2 2 2 2 2 0 2 0 1 0 2 0 2 2 1 2 2 0 2 2 0 0 2 2 0 2 2 1 2 2
 2 1 2 2 0 2 1 1 2 0 1 1 1 2 0 0 1 2 0 0 1 2 2 2 2 2 2 2 1 2 2 0 2 2 2 1 1
 2 1 2 2 1 2 2 0 0 1 2 2 0 2 0 2 1 0 1 2 2 0 2 2 1 0 1 2 2 2 0 2 2 0 2 2 2
 2 2 2 2 2 1 1 0 1 1 2 0 2 1 2 1 2 1 2 2 0 1 2 1 2 1 2 0 2 2 2 2 2 0 1 2 1
 2 0 0 2 1 2 2 1 1 1 0 2 2 0 2 0 2 2 2 2 2 1 2 1 2 1 2 2 0 2 1 2 2 2 1 2 2
 2 0 2 2 1 2 2 2 1 2 2 0 0 2 0 2 2 2 2 2 1 1 0 0 2 1 2 1 2 1 2 1 2 2 2 2 2
 1 0 2 2 2 2 2 2 1 0 0 2 2 2 2 2 2 2 0 2 0 0 2 0 2 1 2 1 1 2 0 2 0 2 2 1 0
 1 2 1 2 2 2 0 2 2 0 1 1 2 2 2 2 2 0 2 2 2 1 2 2 0 0 1 0 0 2 2 2 0 1 2 2 2
 0 1 2 2 2 2 1 2 0 2 2 1 1 2 2 2 2 1 2 2 2 2 2 2 2 0 0 0 1 2 2 0 0 2 2 2 2
 2 1 2 2 2 2 2 0 2 2 2 0 2 2 2 1 0 1 2 2 1 2 2 1 2 1 1 0 2 1 2 1 2 2 0 0 1
 0 1 2 1 2 2 2 2 2 2 2]
Testing...
Train rate: 60.491493:

```
output of cv2.ml.ANN_MLP:
```
(1762, 38400)
(1762, 4)
Loading image duration: 3.847764051
Training MLP ...
Training duration: 824.479784823
Ran for 1 iterations
Prediction: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]
True labels: [2 1 2 0 2 2 0 1 2 2 2 2 2 2 1 2 0 2 2 2 0 0 2 2 1 0 0 0 0 1 2 2 2 2 0 2 1
 1 2 2 2 2 1 2 0 1 2 0 2 1 0 2 0 2 1 2 1 2 2 2 2 2 0 2 0 0 2 2 2 2 2 2 2 2
 2 2 1 2 2 2 2 2 1 1 2 2 2 1 2 1 2 0 2 2 2 1 2 2 1 2 0 0 2 2 2 2 2 2 2 0 2
 2 0 2 0 2 0 1 2 0 2 2 2 2 2 1 1 2 1 0 2 2 0 1 2 2 2 2 2 2 2 1 2 1 1 2 2 2
 2 2 1 1 2 2 2 2 1 1 0 2 0 2 2 2 0 2 2 2 2 1 2 0 2 0 2 2 1 2 1 1 2 0 2 2 0
 2 2 2 0 0 2 2 2 1 0 0 2 2 0 2 2 2 0 2 0 2 1 2 2 2 2 2 0 2 2 1 2 2 2 0 2 2
 1 2 2 0 2 2 0 0 2 2 2 2 2 2 2 0 0 2 2 0 2 2 2 2 1 0 2 2 2 2 0 2 1 2 0 2 2
 0 2 2 2 2 2 0 2 2 0 2 2 0 2 2 2 1 1 2 2 2 2 0 1 2 1 2 0 2 2 2 0 2 2 2 0 2
 1 2 1 2 0 0 1 2 0 2 0 0 1 2 2 2 1 2 2 2 2 2 2 1 2 3 2 2 0 1 2 1 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 1 1 1 1 2 0 0 2 0 2 1 0 2 2 2 2 2 2 2 0 2 2 1 2 2 2 2 2
 2 2 2 2 0 2 2 1 1 0 2 0 2 0 1 2 2 2 2 0 2 2 2 2 2 2 2 2 1 2 2 2 2 1 2 2 0
 2 2 0 2 0 0 1 1 0 2 2 2 2 2 0 2 2 2 2 0 2 0 2 1 0 2 2 2 0 1 1 2 0 0 2 0 2
 2 0 1 0 0 2 2 2 1 0 2 1 2 2 2 2 0 2 2 2 2 2 0 2 2 2 2 2 2 0 2 2 0 2 2 2 1
 2 2 1 2 2 0 2 2 2 2 0 2 2 0 1 2 0 2 2 2 2 0 2 2 2 1 2 0 2 1 2 2 0 2 2 2 2
 0 2 2 2 2 1 2 1 1 2 1]
Testing...
Train rate: 19.848771:

```
Pls help!!!

**Comment by AiBuddy** [comment]
@hamuchiwa  having slightly same problem . please help

**Comment by hamuchiwa** [comment]
Training neural network is non trivial, try to use whole image which may give you a better result. To give you peace of mind, here is a [self-driving video](https://www.youtube.com/watch?v=KrvvmLEQk8o) from aha124226675.

**Comment by smahajan07** [comment]
@hamuchiwa . I seem to have a similar problem, except that I have successfully trained the model (see below). 
But when I'm running rc_driver.py, it is predicting only one output , that is, 'left'. I am still debugging, but open to suggestions.

    Loading training data...
    ['train_labels', 'train']
    (219, 38400)
    (219, 4)
    ['train_labels', 'train']
    (74, 38400)
    (74, 4)
    ['train_labels', 'train']
    (16, 38400)
    (16, 4)
    ['train_labels', 'train']
    (34, 38400)
    (34, 4)
    ['train_labels', 'train']
    (75, 38400)
    (75, 4)
    ['train_labels', 'train']
    (57, 38400)
    (57, 4)
    (475, 38400)
    (475, 4)
    Loading image duration: 1.18788429317
    Training MLP ...
    Training duration: 57.7994991789
    Ran for 30 iterations
    Prediction: [2 2 2 3 2 0 2 0 3 2 2 2 0 0 0 0 0 2 2 0 0 0 2 0 2 2 2 2 0 0 0 0 0 2 1 2 0
     0 2 0 0 0 2 0 2 3 2 2 2 0 0 2 0 0 0 2 2 2 2 1 1 2 2 0 0 0 2 0 0 0 0 0 0 1
     2 0 2 3 2 1 1 2 2 0 0 0 0 0 0 0 0 2 2 3 2 0 0 2 2 1 0 2 0 0 0 0 0 0 2 2 3
     3 2 2 2 2 0 0 0 0 1 2 0 0 0 2 2 2 2 2 1 1 0 3 0 0 0 0 2 1 1 1 3 3 1 1 2 3
     2 0 0 0 0 2 2 1 1 2 2 2 1 1 2 1 1 1 2 2 2 2 2 2 2 1 2 1 1 1 1 1 1 2 1 1 2
     1 1 1 1 2 1 1 3 3 0 2 2 2 2 2 1 2 2 0 2 2 2 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2
     2 2 1 1 2 2 2 2 1 1 2 2 2 1 1 1 1 2 2 2 3 2 2 2 1 2 2 2 2 2 2 1 1 1 1 1 1
     2 2 2 3 1 2 2 2 1 1 1 1 1 2 1 1 1 1 2 2 2 0 0 0 2 1 1 1 1 0 0 2 2 2 2 2 2
     3 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 3 2 2 2 2 2 3 2 2 2 2 2 2 2 3 2
     2 2 2 2 2 2 3 3 3 2 2 2 2 2 2 1 1 0 0 0 0 0 0 0 0 0 0 2 1 1 0 3 3 3 3 3 3
     2 2 0 0 0 0 0 2 0 0 2 3 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 1 1 0
     0 0 0 2 2 2 0 0 0 0 0 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 3 2 2 2 0 0 0 0 0 0 0
     2 0 0 0 0 0 3 3 3 3 3 3 3 3 1 3 2 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
    True labels: [2 2 2 2 2 0 2 0 2 2 2 2 0 0 0 0 0 2 2 0 2 0 2 2 2 2 2 2 0 0 0 0 0 2 1 2 0
     0 2 0 0 0 0 0 2 2 2 2 2 0 0 2 0 0 2 2 2 2 2 1 1 2 0 0 0 0 2 0 0 0 0 0 0 1
     2 2 2 2 2 1 1 2 2 0 0 0 0 0 1 0 0 2 2 2 2 0 0 2 2 1 0 2 0 0 0 0 0 0 2 2 2
     2 2 2 2 2 0 0 0 0 1 2 0 0 2 2 2 2 2 2 1 1 0 0 0 0 0 0 2 1 1 1 1 1 1 1 2 2
     0 0 0 0 0 2 2 1 1 2 2 2 1 1 2 1 1 1 2 2 2 2 2 2 2 1 2 1 1 1 1 1 1 2 1 1 2
     1 1 1 1 2 1 1 0 0 2 2 2 2 2 2 1 2 2 0 2 2 2 1 1 1 1 1 1 2 0 2 2 2 2 2 2 2
     2 2 1 1 2 2 2 2 1 1 2 2 2 1 1 1 1 2 2 2 2 2 2 2 1 2 2 2 2 2 2 1 1 2 1 1 0
     2 2 2 1 1 2 2 2 1 1 1 1 1 2 1 1 1 1 2 2 2 0 0 2 2 1 1 1 1 1 1 2 2 2 2 2 2
     2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
     2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 0 0 2 0 0 0 0 0 0 2 2 1 1 0 0 0 0 0 0 0
     2 2 0 0 0 0 1 2 1 0 2 2 1 1 0 2 0 0 0 0 0 0 1 0 2 2 0 0 0 0 2 0 0 2 1 1 0
     0 0 0 2 2 0 0 0 0 0 0 2 2 2 2 2 2 0 2 0 0 0 0 0 1 1 2 2 2 2 0 0 0 0 0 0 1
     2 0 0 0 0 1 2 0 1 2 1 2 1 1 1 2 2 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
    Testing...
    Train rate: 84.631579:

**Comment by smahajan07** [comment]
Just wanted to mention that I am not exactly using rc_driver.py but an equivalent script just to check predictions of my network and not worry about the ultrasonic sensor or stop signs. I have uploaded it as a gist [here](https://gist.github.com/smahajan07/8e0eb251e706e0e3dc6c32bba0b739db)

**Comment by hamuchiwa** [comment]
@smahajan07 You could do cross validation to see how good the model is performed. Of course, if your keep using the same track then a high accuracy on training set is sufficient, overfitting is irrelevant in this case.

**Comment by smahajan07** [comment]
@hamuchiwa I will try to cross validate my training set and get back, in the mean time could you tell me if the procedure I am following is faulty.

Before training it on dozens of different tracks, I am training it on 2 tracks (straight and then right/left respectively) back and forth. The data being collected is approximately 500 images in total. Using the now generated npz files I'm running the 'mlp_training.py' and getting an xml file.
What concerns me is the training is happening too fast (i didn't expect this on my i5 and integrated graphics card, I have a server but not currently using it for this) and that every time my xml file is approx 35 MB (even though I change my number of training images).

I know these are very trivial concerns,but let me know if you have any suggestions.

Also, what is the minimum number of images that we should train the neural network on?

**Comment by smahajan07** [comment]
@hamuchiwa I am planning to create a branch for this repo where in those who are making this project using an external webcam (and not raspi cam) and use a different streaming method (and not socket server).

**Comment by hamuchiwa** [comment]
@smahajan07 Hi, I think 500 images in total is good enough. If you are not entirely satisfied with your training data, you could "cheat" a bit meaning that you can manually put the car on the track where you think it should be, then create a sample, and then do ti over and over again. Sometimes I found this helpful as I do make mistakes while controlling the rc car, but it is really tedious doing this...

The xml file contains weights and biases for your trained model, the dimension of the weights matrix and bias matrix depends on the architecture of the neural network (layer size) rather than number of samples. If you have a deep neural network then you probably would see the file size increase.

**Comment by smahajan07** [comment]
@hamuchiwa , I cross validated my data set and it looks promising, but I am unfortunately facing the same problem that my [script](https://gist.github.com/smahajan07/8e0eb251e706e0e3dc6c32bba0b739db) (an equivalent to your rc_driver.py, instead only focuses on driving, no signs or distance calculation) is causing some problem and the only output I am receiving is 'LEFT'.

And this cross validation was performed by inputting the complete image and not just half. Also I changed the layer size to [(76800, 64,4)].

        Loading training data...
        ['train_labels', 'train']
        (114, 76800)
        (114, 4)
        ['train_labels', 'train']
        (100, 76800)
        (100, 4)
        ['train_labels', 'train']
        (122, 76800)
        (122, 4)
        ['train_labels', 'train']
        (75, 76800)
        (75, 4)
        (411, 76800)
        (411, 4)
        Loading image duration: 1.81404559868
        Training MLP ...
        Training duration: 509.356298789
        Ran for 76 iterations
        Prediction: [2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 2 1 1 0 0 2 2 0 0 0 0 0
         0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 1 1 1 1 1 1 2 0 0 1 1 1 1 1 1 2 2 2 2
         2 1 1 1 0 0 2 2 2 2 0 0 2 2 0 0 0 2 2 2 2 0 0 0 0 3 3 2 0 0 0 0 0 0 0 0 0
         0 0 0 2 2 2 1 1 1 1 1 1 2 2 0 0 0 0 0 1 1 2 2 2 2 2 0 0 1 1 0 0 0 0 0 0 0
         1 1 1 1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 2 0 0 1 1 1 1 1 1 1 1 1 1 1 1
         1 1 0 0 2 0 1 1 1 2 2 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 0 0 2
         2 1 1 0 1 2 2 2 1 2 2 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1
         1 0 1 1 1 0 0 2 2 1 1 1 1 1 1 1 1 1 0 0 0 2 2 2 2 2 0 0 2 2 2 2 0 0 0 0 3
         2 2 1 1 1 1 1 1 2 2 2 2 2 2 0 0 1 1 0 0 0 2 2 2 0 0 0 0 1 0 0 1 1 1 1 1 1
         1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0
         0 0 0 0 0 0 0 0 0 0 1 1 1 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
         2 2 2 2]
        True labels: [2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 2 2 1 1 0 0 2 2 0 0 0 0 0
         0 0 0 0 0 0 1 1 0 0 0 0 0 2 2 2 2 2 1 1 1 1 1 1 2 0 0 1 1 1 1 1 1 0 0 2 2
         2 1 1 0 0 0 2 2 2 2 0 0 2 2 0 0 3 2 2 2 2 0 0 0 0 1 1 2 0 0 0 0 0 0 0 0 0
         0 0 0 2 2 2 1 1 1 1 1 1 2 2 0 0 0 0 1 1 1 2 2 2 2 2 0 0 2 0 0 0 0 0 0 0 0
         1 1 1 1 0 0 0 1 1 0 2 0 0 0 0 0 0 0 0 0 0 1 2 0 0 1 1 1 1 1 1 1 1 1 1 1 1
         1 1 0 0 2 0 1 1 1 2 2 0 0 0 0 2 2 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 0 0 2
         2 1 1 0 1 2 2 2 2 2 2 0 0 0 0 1 1 0 2 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1
         1 0 1 1 0 0 0 1 1 1 1 0 0 1 1 1 1 0 0 0 0 2 2 2 2 2 0 0 2 2 2 2 0 0 0 0 3
         2 2 1 1 1 1 1 1 2 2 0 2 2 2 0 0 1 1 0 0 1 2 0 2 0 0 0 0 1 0 0 1 1 1 1 1 1
         1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0
         0 0 0 0 0 0 0 0 2 2 1 1 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
         2 2 2 2]
        Train rate: 91.727494:
        ['train_labels', 'train']
        (75, 76800)
        (75, 4)
        (411, 76800)
        (411, 4)
        Testing Prediction: [2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 2 1 1 0 0 2 2 0 0 0 0 0
         0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 1 1 1 1 1 1 2 0 0 1 1 1 1 1 1 2 2 2 2
         2 1 1 1 0 0 2 2 2 2 0 0 2 2 0 0 0 2 2 2 2 0 0 0 0 3 3 2 0 0 0 0 0 0 0 0 0
         0 0 0 2 2 2 1 1 1 1 1 1 2 2 0 0 0 0 0 1 1 2 2 2 2 2 0 0 1 1 0 0 0 0 0 0 0
         1 1 1 1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 2 0 0 1 1 1 1 1 1 1 1 1 1 1 1
         1 1 0 0 2 0 1 1 1 2 2 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 0 0 2
         2 1 1 0 1 2 2 2 1 2 2 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1
         1 0 1 1 1 0 0 2 2 1 1 1 1 1 1 1 1 1 0 0 0 2 2 2 2 2 0 0 2 2 2 2 0 0 0 0 3
         2 2 1 1 1 1 1 1 2 2 2 2 2 2 0 0 1 1 0 0 0 2 2 2 0 0 0 0 1 0 0 1 1 1 1 1 1
         1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0
         0 0 0 0 0 0 0 0 0 0 1 1 1 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
         2 2 2 2 3 3 3 2 3 3 3 3 0 0 3 3 3 3 3 1 1 0 0 2 2 3 0 0 0 0 0 0 0 0 0 0 1
         1 1 2 2 3 3 3 3 2 2 2 2 2 1 1 1 1 1 1 1 2 2 3 3 0 0 0 2 0 2 0 0 1 1 1 1 1
         1 2 2 2 2]
        Testing True labels: [2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 2 2 1 1 0 0 2 2 0 0 0 0 0
         0 0 0 0 0 0 1 1 0 0 0 0 0 2 2 2 2 2 1 1 1 1 1 1 2 0 0 1 1 1 1 1 1 0 0 2 2
         2 1 1 0 0 0 2 2 2 2 0 0 2 2 0 0 3 2 2 2 2 0 0 0 0 1 1 2 0 0 0 0 0 0 0 0 0
         0 0 0 2 2 2 1 1 1 1 1 1 2 2 0 0 0 0 1 1 1 2 2 2 2 2 0 0 2 0 0 0 0 0 0 0 0
         1 1 1 1 0 0 0 1 1 0 2 0 0 0 0 0 0 0 0 0 0 1 2 0 0 1 1 1 1 1 1 1 1 1 1 1 1
         1 1 0 0 2 0 1 1 1 2 2 0 0 0 0 2 2 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 0 0 2
         2 1 1 0 1 2 2 2 2 2 2 0 0 0 0 1 1 0 2 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1
         1 0 1 1 0 0 0 1 1 1 1 0 0 1 1 1 1 0 0 0 0 2 2 2 2 2 0 0 2 2 2 2 0 0 0 0 3
         2 2 1 1 1 1 1 1 2 2 0 2 2 2 0 0 1 1 0 0 1 2 0 2 0 0 0 0 1 0 0 1 1 1 1 1 1
         1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0
         0 0 0 0 0 0 0 0 2 2 1 1 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
         2 2 2 2 2 2 2 2 0 0 2 2 2 2 1 1 1 1 1 1 1 1 1 0 2 2 2 2 1 1 1 1 1 1 1 1 1
         1 2 0 2 2 1 1 2 0 0 1 1 0 0 0 1 2 2 2 2 2 2 2 2 0 0 0 2 2 3 0 0 0 0 0 0 1
         1 1 1 0 2]
        Test rate: 81.481481:
        Process finished with exit code 0

Could you look at my [script](https://gist.github.com/smahajan07/8e0eb251e706e0e3dc6c32bba0b739db) and see if something is wrong?

**Comment by smahajan07** [comment]
@hamuchiwa 
I'm so sorry, there was a very minor bug in my code. It was not looking in the right folder. :/
I apologize for the confusion, and thanks for your help.

Everything is fine, except my the response is a little delayed. Do you have any suggestions to speed up the response?

**Comment by hamuchiwa** [comment]
@smahajan07 You could lower the image resolution, or maybe create a buffer and use two threads, one for just getting image from camera, another for streaming. Another "quick" way is to make your car go slower...

**Comment by denisrexhepi** [comment]
> @hamuchiwa I am planning to create a branch for this repo where in those who are making this project using an external webcam (and not raspi cam) and use a different streaming method (and not socket server).

Did you manage to do it?
