### ISSUE TITLE
questions about the communications 

### ISSUE THREAD

**Issue by Abdalrazak-Mansour** [hamuchiwa/AutoRCCar#6]
can you give me an idea on how you got the video streaming from the camera to pc ?

**Comment by hamuchiwa** [comment]
It's a client to server communication, where Raspberry Pi is the client, PC is the server. Images are converted into byte stream on Raspberry Pi and sent to PC over wifi connection. PC receives and decodes the data back to images.

**Comment by Abdalrazak-Mansour** [comment]
thank you for replying, you have been a great help.
I have a second question, what is the software you used to accomplish that wifi connection, is it Perforce !!
anyway can you guide me to a tutorial to accomplish it
thanks in advance.
