### ISSUE TITLE
ultrasonic_client.py error 

### ISSUE THREAD

**Issue by ortengtx** [hamuchiwa/AutoRCCar#62]
hello , thank you for shearing the code 
im just getting  this error while running ultrasonic_client.py on raspberry pi 
hope you can help me solving this problem 

>> %Run ultrasonic_client.py
  File "/home/pi/ultrasonic_client.py", line 56
    print "Distance : %.1f cm" % distance
                             ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by hamuchiwa** [comment]
In python3 print is a function which requires ().
