### ISSUE TITLE
Circuit Diagram

### ISSUE THREAD

**Issue by hsharma27** [hamuchiwa/AutoRCCar#64]
Can anyone please tell me about the circuit connections between remote controller of car and arduino just shorted out 3 arduinos.
PS : Can we please mention the car model being used it would be a great help.

**Comment by isamabdullah88** [comment]
I am also having the same problem. If you got a solution, please share with me.

**Comment by isamabdullah88** [comment]
Hi @hsharma27 ,
Please look at this:
https://github.com/hamuchiwa/AutoRCCar/issues/61

**Comment by hsharma27** [comment]
Hi @isamabdullah88 Thanks a lot bro this completely solved my confusion.

**Comment by isamabdullah88** [comment]
Hi @hsharma27 , Did you solve the problem? I am still having some issues. If you can help, I would be grateful.

**Comment by hsharma27** [comment]
I changed the car to the one shown in the blog mentioned in #61 i.e yellow lambhorghini.
