### ISSUE TITLE
mlp_training memory error

### ISSUE THREAD

**Issue by lakshand8** [hamuchiwa/AutoRCCar#67]
I've been getting an error when I try to run the mlp_training script. This error only comes up if there are more than 50 .npz files are in the training data folder. Currently I have 73 .npz files and 1027 images to train the network. Can someone please help me with this error? 

> C:\Python27\python.exe C:/Users/ldedi/Documents/GitHub/AutoRCCar/computer/mlp_training.py
Loading training data...
Traceback (most recent call last):
  File "C:/Users/ldedi/Documents/GitHub/AutoRCCar/computer/mlp_training.py", line 26, in <module>
    image_array = np.vstack((image_array, train_temp))
  File "C:\Python27\lib\site-packages\numpy\core\shape_base.py", line 237, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
MemoryError

Update: This was fixed by changing python version to 3.4 and 64bit. It turned out the 32bit Python has a memory limit of 2gbs. To get the OpenCv 3 working with 64bit python, you have to install the unofficial package. Also don't forget to update the print lines in the 2.6 version to reflect the 3.4 python

**Comment by hamuchiwa** [comment]
Thanks a lot~
