### ISSUE TITLE
streaming error from client to server- ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by Rahul16697** [hamuchiwa/AutoRCCar#70]
Traceback (most recent call last):
  File "/home/pi/stream/stream_client.py", line 23, in <module>
    connection.flush()
  File "/usr/lib/python3.5/socket.py", line 594, in write
    return self._sock.send(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/stream/stream_client.py", line 32, in <module>
    connection.close()
  File "/usr/lib/python3.5/socket.py", line 594, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by aakashm301** [comment]
What where you running ? Collect_trainning_data.py ? or another file ?

**Comment by kaskagorry** [comment]
I have the same problem

I execute "collect_training_data.py" in PC, and in Raspberry i execute "stream_client.py" and i receive the same error.

Do you have the solution to this error?

**Comment by Rahul16697** [comment]
I had and resolved it ....check the IP properly and port too ....thts the problem.......try the raspberry pi ip if it din work try with ua PC IP
