### ISSUE TITLE
RC car Remote

### ISSUE THREAD

**Issue by Gooose1909** [hamuchiwa/AutoRCCar#73]
I couldn't find a rc car like you used . So had to go for different one . But mine has 4 tactile pins . Even with little electronic knowledge i find the connection of it way too confusing . struggling with wire connections.

Anyone had this issue ?

**Comment by hsharma27** [comment]
What did you use for connection please share @Gooose1909

**Comment by Gooose1909** [comment]
I was initially unable to interface my arduino to rc car remote
But i went with RF transmitter and reciever and made an RC car of my own

**Comment by hsharma27** [comment]
kkk Thnx

**Comment by MuhammadAnwarKhan** [comment]
@Gooose1909  Can you briefly explain how did you make your car using your own RF transmitter and reciever??
