### ISSUE TITLE
Collect_training_data

### ISSUE THREAD

**Issue by Gooose1909** [hamuchiwa/AutoRCCar#75]
When i run this collect training data script . 
It seems to run fine 
Even prints forward , left , right in shell 
But still my training_data folder is empty . Why ???

**Comment by hamuchiwa** [comment]
Press 'q' to break the loop, then data is saved in "training_data" directory.

**Comment by Gooose1909** [comment]
I tried
It didnt work

**Comment by hamuchiwa** [comment]
Are you able to output the image array during streaming?

**Comment by Gooose1909** [comment]
No , 
Its like i get a window showing camera stream from my pi 
And frames are saved in training_images 
But my training_data is empty even though if i press 'q'

**Comment by Gooose1909** [comment]
@hamuchiwa can you contact me here : 
sugan170@gmail.com
I really need your help . Planning to tweak some changes that's why

**Comment by hamuchiwa** [comment]
Are you using windows, mac or linux? Have you tried setting an absolute folder path?

**Comment by Gooose1909** [comment]
Windows

**Comment by KhyatiMehta3** [comment]
Hi, I have the same problem. Also, I wanted to know why you're connecting to a serial port in this script? All the driving commands are also written to the same serial port ( Like self.ser.write(char()) ) I don't understand the reason for this.

**Comment by hamuchiwa** [comment]
@Gooose1909 @KhyatiMehta3 If "train" numpy array is not empty, then I would say it's something to do with the path. Is absolute path working?

**Comment by Gooose1909** [comment]
I found my problem was by absolute path
But @hamuchiwa is there a way to control car without remote
Like adding motor driver to pi and wirelessly controlling like server and
client!??

**Comment by hamuchiwa** [comment]
@Gooose1909 I haven't done it myself, but there are people discussing and trying to do it with raspberry pi only.

**Comment by Gooose1909** [comment]
@hamuchiwa can you please explain how u have interfaced remote to arduino briefly 
Please.

**Comment by hamuchiwa** [comment]
@Gooose1909 Computer sends the prediction value to Arduino, and then Arduino sets high or low to its pins which are connected to the remote. 
In the case if you would like to use Raspberry Pi, like you mentioned earlier, the computer sends the prediction back to pi and then pi controls the motor accordingly.

**Comment by Gooose1909** [comment]
@hamuchiwa
I meant like cicuit connection
Like did u connect batteries to the remote
Or u used the 3.3v from arduino
And also i have doubt like did u use optoisolator or not

**Comment by hamuchiwa** [comment]
@Gooose1909 I used AA battery for the remote, although I think using optoisolator is a better way to do it.

**Comment by arunph** [comment]
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitte.  
I m having above error when I run collect_training_data.py
