### ISSUE TITLE
The Car drive wrong way !

### ISSUE THREAD

**Issue by marcusvn** [hamuchiwa/AutoRCCar#78]
I do all work for the Car but when I run Rc_Driver.py, The Car drives wrong way. Anyone have any idea to help me?

**Comment by hamuchiwa** [comment]
Number of images and data quality can both affect the result, what is the accuracy of your model?

**Comment by marcusvn** [comment]
Just 50% after run mpl_tranning. So I should collecting a lot of data or what ?

**Comment by hamuchiwa** [comment]
0.5 is too low, you need at least 0.8 to generate good result. For a simple short track, roughly 200 images should be enough.

**Comment by marcusvn** [comment]
Should I use Collecting_Tranning_Data for a lot of times or just use it one two times?

**Comment by marcusvn** [comment]
When I running first Collecting_Tranning Data again!
![Uploading image.png…]()

**Comment by marcusvn** [comment]
When I running first Collecting_Tranning Data again!
![image](https://user-images.githubusercontent.com/35937697/37499994-7e5d8858-28f9-11e8-8d34-f2df0970a4de.png)

**Comment by hamuchiwa** [comment]
I would suggest collecting multiple files, it's just easier to do in that way in case you need to discard any data. All individual files will be merged together in the training phase.

**Comment by marcusvn** [comment]
Collecting tranning file when train accurcy reach 0,8 that right?

**Comment by hamuchiwa** [comment]
Yes, you can try with a straight line, a left turn, then a right turn, and see what happens.

**Comment by marcusvn** [comment]
Thanks For helping me! I will test again! If I encounter problems I will bother you! thanks!

**Comment by kxrf97** [comment]
@marcusvn did you manage tackle the training problem?
