### ISSUE TITLE
mlp training.py abruptly gets closed

### ISSUE THREAD

**Issue by avisrivastava254084** [hamuchiwa/AutoRCCar#80]
Running the file sometimes generates the results: test and  training accuracy but sometimes it ends abruptly without any display of the results.

**Comment by hamuchiwa** [comment]
Does it give you any errors?

**Comment by avisrivastava254084** [comment]
@hamuchiwa 
Sorry, my bad, the issue was resolved. Actually there was no issue at all, my IDE was corrupt.
