### ISSUE TITLE
How to control the telecontroller of the car?

### ISSUE THREAD

**Issue by Maxxiezhu** [hamuchiwa/AutoRCCar#82]
I don't know the arduino's  pin how to connect  of the PCB.By the way,my rc-car is same with you. Could you tell me ?

**Comment by hamuchiwa** [comment]
Take a look at this [thread](https://github.com/hamuchiwa/AutoRCCar/issues/61).

**Comment by Maxxiezhu** [comment]
Thank you very much.Now,I tried to do @hamuchiwa
