### ISSUE TITLE
Raspberry Display

### ISSUE THREAD

**Issue by hsharma27** [hamuchiwa/AutoRCCar#87]
I am using VNC Player for displaying raspberry display and it is giving me error for picamera. So where am I going wrong ? should i go with hdmi display or VNC Player ? What did you guys used ? Thanks in advance

**Comment by Gooose1909** [comment]
Raspberry display in the sense for displaying the screen of raspberry pi
If yes
I would recommend u to use remote desktop connection app
Which is inbuilt in windows

**Comment by hsharma27** [comment]
But then why is it giving me error in picamera (Using VNC Player and Raspbian Jessie).

**Comment by Gooose1909** [comment]
If u are facing error while raspistill
Then this might be the reason :
The preview is a superimposed video layer on top of whatever desktop or
console you are using and is therefore not available for VNC to
send/receive.

You could try network streaming.
