### ISSUE TITLE
Remote Control of the Car..

### ISSUE THREAD

**Issue by Cagriyoruk** [hamuchiwa/AutoRCCar#88]
I am having a problem with controlling the car via python (keyboard).I found and soldered the wires I have to solder.Then I upload the code to the Arduino.After that, I opened the rc_control_test and tried to run the code.There were no problems with forward and right but the reverse and left didn't work.I tried everything in the threads.The level shifting also voltage dividing.But couldn't solve the problem.I did nearly 15 possible circuit combinations.But no result.I hope that you guys can give me hints.
![ecf28cfe-2644-49a9-bbb7-ea6d3d28ad59](https://user-images.githubusercontent.com/36968687/37864355-7bdd0cb2-2f7e-11e8-9113-3f51d0fe66a8.jpg)
![67cdbd7b-8f32-4920-9ffe-3ea561670633](https://user-images.githubusercontent.com/36968687/37864358-821370a8-2f7e-11e8-8427-6643a4173aff.jpg)

**Comment by Cagriyoruk** [comment]
They are not negative.But there is something wrong.When is feed the circuit with the 5v Arduino output, The open circuit voltage is nearly 5v.When I press just forward right has 0.44V.Left and reverse have 0v.When I press left or reverse the 5v is coming but they're not reacting.No LED light no car movement.But when Measuring it I am seeing the 5v.In total just forward, right and forward right is working :/. I tried to feed it with both the Arduino and the 2 AA batteries total 3.1V.When I fed it with the 3.1V they couldn't communicate with the Arduino and no car movement again.
![461d12d4-4316-4a35-a327-9000d74e6036](https://user-images.githubusercontent.com/36968687/37865231-97637e9c-2f8a-11e8-985d-a65d71622d8c.jpg)

**Comment by Gooose1909** [comment]
Thats the problem with current model remote
No proper way of interfacing arduino with it
I tried 3 different remote and failed
I really recommended you to use an rf transmitter and reciever

**Comment by Cagriyoruk** [comment]
There are some people who had the same issue with the remote.But I think they've solved the problem.I tried to do the same thing but again no result.
Here is an example:
https://arduino.stackexchange.com/questions/21205/controlling-an-rc-car-using-arduino
I tried to implement the solution but didn't work out at all.
I don't think I can use the rf transmitter and receiver in this case.My car has some problems I tried to communicate with the Bluetooth module and made a direct connection through Arduino pins and the motor.

**Comment by Gooose1909** [comment]
http://blog.davidsingleton.org/nnrccar/
Try this method and say your results

**Comment by Cagriyoruk** [comment]
I tried the method but it didn't work out.But I found another solution.I use optocouplers as a switch.And now all possible combinations are working.Here is the solution I found.I used 5k resistors instead of 10k.Built the circuit 4 times for each direction.Got the VCC from Arduino's 5v.If you have any questions feel free to ask.

![bb](https://user-images.githubusercontent.com/36968687/38012610-c8c4992a-326a-11e8-8c97-a6cbda373e60.jpg)

![20180328_093247](https://user-images.githubusercontent.com/36968687/38012809-86b09844-326b-11e8-959a-6acb9fda24ad.jpg)

**Comment by Moha-alfridi** [comment]
Can you please share a clear schematic, I am having this problem, with my model.

signal input and signal GND, is it the remote signal?
what is the AVR?

Instead of using optocouplers , can I build it using mosfit ?

**Comment by kxrf97** [comment]
@Cagriyoruk i have the same controller as yours, do you mind to help me with setup
