### ISSUE TITLE
Serial port about could not open port 'COM4(Arduino/Genuino Uno

### ISSUE THREAD

**Issue by Maxxiezhu** [hamuchiwa/AutoRCCar#90]
I'm sure that I'm not mistaken the serial port of my PC.
But,PC show this when I  run the "rc_control_test"
Please tell me why, thank you very much.
![360 16751105385576](https://user-images.githubusercontent.com/37396232/38168830-f5cf2a34-358a-11e8-94d7-6a3b52496fd4.png)
![360 16530715508947](https://user-images.githubusercontent.com/37396232/38168831-f9e9ca52-358a-11e8-9a14-264e2c2a8eca.png)
![360 16730302658457](https://user-images.githubusercontent.com/37396232/38168833-fedbc5d8-358a-11e8-8364-d44973f32318.png)

**Comment by Gooose1909** [comment]
Running CMD as admin might solve the problem

**Comment by hamuchiwa** [comment]
@Maxxiezhu 括号的内容去掉，只留‘COM4’试一下

**Comment by Maxxiezhu** [comment]
@hamuchiwa 我明白了，之前是我错了，应该是COM4，但是还是提示无法打开通讯。还有个问题是用python_IDE环境下打开那个rc_control_test文件吗？

**Comment by Gooose1909** [comment]
@maxxiezhu
Changing ur port number may fix it

**Comment by Maxxiezhu** [comment]
@Gooose1909 Unable to modify...

**Comment by Gooose1909** [comment]
From the Windows desktop, right-click on My Computer. Then Properties >
Hardware, Device Manager > Ports (COM & LPT). There will be an entry like
"USB Serial Port (COM4)". This means serial comm port 4 is the one in use.

Change it to port 8 or something thats not in use then try it

**Comment by hamuchiwa** [comment]
@Maxxiezhu 我用的是pycharm，不过终端打开应该也行。我觉得可以先试一下Arduino自己带的样例文件，看看文件能不能刷到板子上。Gooose1909说的那些方法试过了没，管不管用？

**Comment by Gooose1909** [comment]
My Computer -> Manage -> Device Manager -> Ports -> Communications Port -> Port Settings -> Advanced -> COM Port Number
Sorry this is the right directory to change port value

**Comment by Maxxiezhu** [comment]
ok,,I  change it to port8. And the PC Show this. And the Arduino's signal led flashed.
![360 16610729305935](https://user-images.githubusercontent.com/37396232/38169516-7bbb9f3e-359e-11e8-8f83-5317a0b64b75.png)

The desktop create a file (__pycache__)
![360 1664032882106116](https://user-images.githubusercontent.com/37396232/38169522-ba53845a-359e-11e8-9bb1-fa2af50a226b.png)
![360 16270904656357](https://user-images.githubusercontent.com/37396232/38169523-bc508456-359e-11e8-8bac-a8b59a2f0391.png)

What do I do next?How do I know it  communicate successfully?
@Gooose1909 @hamuchiwa

**Comment by Maxxiezhu** [comment]
@hamuchiwa 我Arduino板子是正常的可以下载程序进去的

**Comment by aakashm301** [comment]
I was also facing the same problem on the laptop I changed the address mine is COM6. And I ran the code in pycharm but nothing happened it just showed that it is running.

**Comment by hamuchiwa** [comment]
@Maxxiezhu 先禁用COM4，然后再重新启用~?

**Comment by Maxxiezhu** [comment]
@hamuchiwa @Gooose1909 
And I've already installed pyserial.
![360 1662062293105113](https://user-images.githubusercontent.com/37396232/38183583-17a39da4-3674-11e8-8acd-5377d27a41bc.png)

But, I had this problem when I was running the code that "rc_control_test". 
![360 16240205396251](https://user-images.githubusercontent.com/37396232/38183595-267f382e-3674-11e8-97ac-73e521c16119.png)

How to deal with this situation?

**Comment by Maxxiezhu** [comment]
@hamuchiwa 你好，上面问你的那些问题处理之后没有再次出现了。但是我想问一下。
1. 运行那个rc_control_test测试文件，怎样才说明测试正常？成功测试？
2.我运行完之后命令窗口弹出来，是这样的
![000000](https://user-images.githubusercontent.com/37396232/38194831-9c955524-36ac-11e8-839e-7267e51d76b3.png)
命令窗口里面没有任何信息，也不能在命令窗口输入任何东西这样正常吗？不过我测试文件运行成功之后，同时Arduino板通信口tx闪烁了一下
3.还有就是为什么运行文件之后，桌面生成一个文件夹？里面是一个pyc文件
![360 16570213757271](https://user-images.githubusercontent.com/37396232/38194876-e670e7c6-36ac-11e8-8def-9ae551677a54.png)
麻烦你给我解答一下这些问题，十分感谢。

**Comment by Maxxiezhu** [comment]
@hamuchiwa 方向键是RC遥控器上面的按键对吧？

**Comment by hamuchiwa** [comment]
@Maxxiezhu 键盘上的方向键，等于是拿键盘当遥控器使。

**Comment by Maxxiezhu** [comment]
@hamuchiwa 
你好，我运行之后，出现这个命令窗口，并且我也把光标放在窗口外，然后用计算机键盘分别按了上下左右，小车没有任何反应。这个是什么问题？四个按键按下去PC也没有任何显示。还是说我按按键的方法错了？
![4654](https://user-images.githubusercontent.com/37396232/38223210-43816d36-371c-11e8-9adf-87e1330c2dcb.png)

**Comment by Maxxiezhu** [comment]
@hamuchiwa 
你好，加了那两行代码之后，成功连接上Arduino了。但是有个问题。我运行代码之后。弹出来了命令窗口和一个pygame的窗口。
![1212](https://user-images.githubusercontent.com/37396232/38229877-89f902d0-373d-11e8-9949-3cb85d082ff1.png)

然后我在pygame出口处，按下我键盘上面的上键下键左键右键都不行。他这样提示我的。
![1516312](https://user-images.githubusercontent.com/37396232/38229881-909e57b6-373d-11e8-9e63-4fd2d117751c.png)

不知道怎么办。麻烦你帮我一下

**Comment by Maxxiezhu** [comment]
@hamuchiwa 
你好之前问你的问题，我尝试了一下，我去掉了chr直接改成读取数字之后，上面的问题没有出现了。然后我再点击键盘上下左右，看到命令窗口显示了按键的方向。
![360 1633011163107111](https://user-images.githubusercontent.com/37396232/38245081-581607d6-376f-11e8-9ad1-5b0328e3c20a.png)
![360 166107299393120](https://user-images.githubusercontent.com/37396232/38245083-59bdd532-376f-11e8-8fa7-7d11517f9969.png)

但是有问题出现了
1.Arduino对应的引脚没有变成低电平去触发小车运动。但是当我每按下一个键盘按键时Arduino的RX串口都闪烁了一下，说明Arduino已经读取了Pc发送的信息，但是小车就是不能运动。是因为我去掉了char的原因吗？

**Comment by Maxxiezhu** [comment]
你好，我找到解决方法了。我已经解决了。谢谢你后面加上这个函数就没有问题了。测试成功！

**Comment by hamuchiwa** [comment]
@Maxxiezhu 方便的话能不能留一下系统和环境的配置？以后要有其他人遇到类似问题我就把他们指到这儿。再想问一下encode()函数的默认参数是什么，会不会是因为中英文系统而导致的不同？
