### ISSUE TITLE
Problem with Ultrasonic sensor

### ISSUE THREAD

**Issue by marcusvn** [hamuchiwa/AutoRCCar#91]
When I run Ultrasonic_client in Pi, The RC car can't move because it has an obstacle in front, How Can I fix it?
![image](https://user-images.githubusercontent.com/35937697/38213449-61fe7438-36eb-11e8-951a-892f2d144727.png)

**Comment by Gooose1909** [comment]
Did u connect the trig and echo pins correctly to the pin number in the
program??

**Comment by Gooose1909** [comment]
Did u check if your ultrasonic sensor is working with simple program??

**Comment by marcusvn** [comment]
When I use ultrasonic sensor test, I think it working but when I run rc_driver it already "Stop, obstacle in front"

**Comment by hamuchiwa** [comment]
@marcusvn There is a threshold set to 30, from your picture the measurement is 9, anything blocking the ultrasonic sensor?

**Comment by marcusvn** [comment]
What is the blocking ultrasonic sensor? I do not understand?

**Comment by Gooose1909** [comment]
Did u change anything in the code???

**Comment by marcusvn** [comment]
No I don't change anything in code!

**Comment by marcusvn** [comment]
@hamuchiwa  Did you connect Ultrasonic sensor direct with Raspberry Pi ?

**Comment by marcusvn** [comment]
When I run for test Ultrasonic Sensor I had limited distance ?
![image](https://user-images.githubusercontent.com/35937697/38256508-b1c1a4ac-3788-11e8-973f-e3370640df4a.png)

**Comment by hamuchiwa** [comment]
@marcusvn The ultrasonic sensor is connected to the pi with some resistors in between. Measurements from your ultrasonic sensor are below 30, that's why the rc car is not moving. Is there something in front of the sensor?

**Comment by marcusvn** [comment]
Nothing in front of the sensor! but I connect directly to the sensor with pi? Have a problem with direct connect?

**Comment by hamuchiwa** [comment]
@marcusvn I followed these [two](https://www.raspberrypi-spy.co.uk/2012/12/ultrasonic-distance-measurement-using-python-part-1/) [tutorials](https://www.raspberrypi-spy.co.uk/2013/01/ultrasonic-distance-measurement-using-python-part-2/), but I chose different value resistors.

**Comment by arunph** [comment]
PlZ @marcusvn help me with your connection pics of ultrasonic sensor with respberry pi
