### ISSUE TITLE
关于树莓派和计算机网络通讯问题

### ISSUE THREAD

**Issue by Maxxiezhu** [hamuchiwa/AutoRCCar#96]
你好，我是台式电脑，树莓派和计算机是要在同一个局域网内吗？台式要怎么弄@hamuchiwa

**Comment by hamuchiwa** [comment]
台式机不影响呀，同一个局域网内就可以了

**Comment by Maxxiezhu** [comment]
那么我用360随身wifi，让台式主机发射无线网络，然后让树莓派连接这个无线网络。可以实现你那种局域网吗？@hamuchiwa

**Comment by hamuchiwa** [comment]
如果是跟路由器一样的东西，树莓派能找到主机ip就行。
