### ISSUE TITLE
About Training Data

### ISSUE THREAD

**Issue by marcusvn** [hamuchiwa/AutoRCCar#97]
Hello, @hamuchiwa  I have some question about train data. Can I use train data for any road I set up? Or when I set up new road I need train again?

**Comment by hamuchiwa** [comment]
In that case, you need to collect data on all possible roads and train the model with all of them.

**Comment by tiachachat** [comment]
Hello, @hamuchiwa i have probleme with training model 
I got this error
    model = cv2.ANN_MLP()
AttributeError: 'module' object has no attribute 'ANN_MLP'

**Comment by hamuchiwa** [comment]
@tiachachat Since you are using OpenCV3, please take a look at this [thread](https://github.com/hamuchiwa/AutoRCCar/issues/60#issuecomment-356751492), I'll close this thread for now.
